### ISSUE TITLE
MinSdkVersion 16

### ISSUE THREAD

**Issue by jjvargas** [Stuart-campbell/RushOrm#1]
Would it be possible in the future to lower the minSdkversion to 14 at least?

**Comment by Stuart-campbell** [comment]
I shall look at that tomorrow, but should not be a problem.

**Comment by Stuart-campbell** [comment]
The jar should already work on 14 even though the project is set to a min of 19.

**Comment by planiel** [comment]
Except that it doesn't. The problem is android 4.0 uses sqllite version 3.7.4, which doesn't support mass-insert.

**Comment by Stuart-campbell** [comment]
Didn't notice that.

Looks like updating to be backwards compatible is possible though from this post.

http://stackoverflow.com/questions/1609637/is-it-possible-to-insert-multiple-rows-at-a-time-in-an-sqlite-database

As of now looks like min SDK is 16 (4.1)

**Comment by Stuart-campbell** [comment]
As of version 1.1.2 Rush will use bulk inserts above android 4.1 or single inserts below. As far as I can tell there are no sql calls not supported from day 1 of android and the no api calls from after Android api 4. 

I have only tested back to 14 though.

**Comment by planiel** [comment]
Awesome! thanks.
