### ISSUE TITLE
Error after trying to search

### ISSUE THREAD

**Issue by herrmartell** [Stuart-campbell/RushOrm#101]
On a clean install of the app, I run this piece of code for a search

`List<UserData> results = new RushSearch()
                    .find(UserData.class);`

Clearly, the first time the app runs it has nothing stored on the dbb.

Yet, I am getting this error:

>E/AndroidRuntime: FATAL EXCEPTION: main
                                                                 Process: com.avena.avena, PID: 31352
                                                                 java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.String co.uk.rushorm.core.AnnotationCache.getTableName()' on a null object reference
                                                                     at co.uk.rushorm.core.RushSearch.buildSql(RushSearch.java:90)
                                                                     at co.uk.rushorm.core.RushSearch.find(RushSearch.java:41)
                                                                     at com.avena.avena.dashboard.Profile.onCreateView(Profile.java:101)

Could you please give me a hand with this?

EDIT:

Suddenly is giving me the same error on every single search, on every single place where I have a search, no matter where am I trying to search for.

**Comment by stuart-apadmi** [comment]
Hi,

This is likely to be one of of two things.

Either you are manually setting the included classes on the RushConfig and have missed out the "Profile" class or you are calling search before initialization has completed.

If it it neither of those things let me know and ill see if I can debug further.

Thanks

**Comment by herrmartell** [comment]
I managed to fix it, based on this [#99](https://github.com/Stuart-campbell/RushOrm/issues/99), and this [#74](https://github.com/Stuart-campbell/RushOrm/issues/74).

Official documentation mentions nothing about setting the classes manually, and it has been working just fine up until yesterday.

**Comment by Stuart-campbell** [comment]
Just closing a few open issues.

Setting the package name is now required which resolved this issue.

Thanks
