### ISSUE TITLE
Failed to get Gradle

### ISSUE THREAD

**Issue by DannyLamarti** [Stuart-campbell/RushOrm#104]
When I add the gradle dependency ('co.uk.rushorm:rushandroid:1.1.11') to my Gradle file it says:

Error:(29, 13) Failed to resolve: co.uk.rushorm:rushandroid:1.1.11

Is there a way to get the Gradle running?

**Comment by Stuart-campbell** [comment]
Hi,

Have you added this to you gradle file?

    repositories {
       maven {
           url "http://maven.rushorm.com"
       }
    }

Thanks

**Comment by DannyLamarti** [comment]
Its working now! Thanks for the quick response :D

**Comment by rr0055256** [comment]
After adding the maven dependency, getting the below error

repositories {
        jcenter()
        url "http://maven.rushorm.com"
    }

Error:(18, 0) Could not find method url() for arguments [http://maven.rushorm.com] on repository container.
<a href="openFile:/Users/galaxy-user/StudioProjects/PopularMovieApp/build.gradle">Open File</a>

**Comment by Stuart-campbell** [comment]
Its not on jcenter it's a private server. Repalce what you have with this:

    repositories {
        maven {
            url "http://maven.rushorm.com"
        }
    }

Thanks

**Comment by rr0055256** [comment]
Thanks Stuart. It worked.

Regards,
Raman
