### ISSUE TITLE
getId wrong return type

### ISSUE THREAD

**Issue by SoAddicted** [Stuart-campbell/RushOrm#11]
Hey, on your website it says 

```java
@Override
        public long getId() { return RushCore.getInstance().getId(this); }
```

But unfortunately you changed it to String

**Comment by Stuart-campbell** [comment]
Thanks for pointing that out. I'v updated the website, it was changed from long to String at beta 0.8.0. The reason for changing it to a String is so ids are unique which makes data import and export between databases possible.

Thanks
