### ISSUE TITLE
UI Freeze when using RushCore.getInstance().deleteAll(Class)

### ISSUE THREAD

**Issue by zoharyosef** [Stuart-campbell/RushOrm#111]
Only happens after a significant amount of re-installs.
On LogCat the following line appears on every freeze:
D/RushOrm: VACUUM;

It gets worse and worse, I got to 40 sec freeze, and only after i erased the app and re-installed, it was gone, temporarily.

As a workaround now i'm using delete() after RushSearch(), and there are no freezes, for now...

Thanks for this great lib! and Good luck

**Comment by Stuart-campbell** [comment]
Opps can't believe I forgot the async version of that call. I will have to get that added.

Thanks

**Comment by Stuart-campbell** [comment]
As of v1.2.0 you can not pass in a RushClassback into the deleteAll function which makes it async.

Thanks

**Comment by zoharyosef** [comment]
Thanks!
