### ISSUE TITLE
Suport for Join Queries

### ISSUE THREAD

**Issue by mayur-mi** [Stuart-campbell/RushOrm#12]
Hi. I am really impressed with this and just curious to know if it is possible to have result from join queries. I have not tried this out yet, but searched all over the internet for this without any success. May be you could help.

I have read all the documents at the website but all of them uses a single table/object when using the standard api of the library. Can we have the result to handle data from multiple tables which has primary and foreign keys? If yes, please suggest and provide a valid solution for it as i currently cant think of getting this implemented. I really want to use this ORM. I currently am using the sugar ORM but have not got success with this yet. Please advice.

Thanks.

**Comment by dco5** [comment]
see if this helps (if this is what you are trying to accomplish)
@RushTableAnnotation
public class Event extends RushObject{
//properties
.....

    @RushList(classname = "com.example.models.Speaker")
    private List<Speaker> Speakers;

    public List<Speaker> getSpeakers() {
        if (Speakers != null) {
            return Speakers;
        }
        return new ArrayList<Speaker>();
    }

    public void setSpeakers(List<Speaker> speakers) {
        Speakers = speakers;
    }
}

Then I just do this to get all events:
ArrayList<Event> events =  RushSearch().find(Event.class);

Then if I want to get all the speakers of events I just do this:

ArrayList<Speaker> speakers = event.getSpeakers();

If I understood your comment then this will help.

**Comment by mayur-mi** [comment]
What if i want to have specific speakers with some ids i get with join queries like 
SELECT * FROM EVENT LEFT JOIN SPEAKER ON EVENT.SPEAKERID=SPEAKER.SPEAKERID
can i have the Objects with the RushORM?

**Comment by Stuart-campbell** [comment]
If I understand correctly. You want to add a where clause to a left join query? i.e you want to load a subset of children?

Is that correct?

**Comment by Stuart-campbell** [comment]
Are you basically looking to be able to perform the search below? Please note the search does not currently exist.

Event event;
List<Speaker> speakers = new RushSearch()                                
                                .whereChildOf(event, "speakers")
                                .and()
                                .whereId("id")
                                .and()
                                .whereId("id").find(Speaker.class);

**Comment by mayur-mi** [comment]
Exactly. Filter out the results that are having same ids in both/all the tables i join. Actually this is because i like Join queries on large databases. I am working on an application that has posts, users, comments, likes, followers, and all.. 
For example I have a table named Posts, with some entries.
Posts are made by the users, so i would have the user ids into the posts table. 
The Users are in another table.
I would like the query result (The object) to contain the user details for each post with the post details as well. 

I am a php developer, turned into an android developer, so I like to work with table joins. It makes a life much more easier. Was wondering if RushOrm can actually return these type of results with select queries.

**Comment by mayur-mi** [comment]
I am wondering i may need to make a separate model for the join results so that the ORM can assign the values. I will get back with a solution, if i find one. Also keep looking here in hope for a solution. :)

**Comment by mayur-mi** [comment]
Take this scenario:

Table 1 
====================
id1  |  name1  |  title1                |   id2
1       aaaa         aaaaaaaaa     |  1
2       bbbb         bbbbbbbbb     |  1
3       cccc          cccccccccc     |  2
4       dddd         ddddddddd    |  3
5       eeee         eeeeeeeee    |  2

Table 2 
==========================
id2  |  name2  |  title2       
1       fffffff         ffffffffffffffff
2       gggg        ggggggggg
3       hhhh        hhhhhhhhh
4       iiiiiiiiii         iiiiiiiiiiiiiiiiiiiiiii
5       eeee        jjjjjjjjjjjjjjjjjjjjjjj

SQL: 
SELECT * 
FROM TABLE1 
LEFT JOIN TABLE2 
ON TABLE1.id2 = TABLE2.id2

This would give me a result set like this
RESULT
====================================================
id1  |   name1   |   title1              |   id2   | name2   | title2
1        aaaa          aaaaaaaaa       1        ffffffff        fffffffffffffffff
2        bbbb          bbbbbbbbb       1        ffffffff        fffffffffffffffff
3        cccc           cccccccccc       2         gggg       ggggggggg
4        dddd          ddddddddd       3        hhhh        hhhhhhhhh
5        eeee          eeeeeeeee       2        gggg        ggggggggg

**Comment by Stuart-campbell** [comment]
The results need to map to a Java class.

That example in classes would look like.

    class Table1 extends RushObject {
         String name;
         String title;
         Table2 table2;
    }

    class Table2 extends RushObject {
         String name;
         String title;
    }

    List<Table1> table1s = new RushSearch().find<Table1>();

   
The idea of database ids and joins is all handled under the hood so that you just need to work with Java objects.

If you wanted to work directly with the results of a join you would need to run raw queries to get the Cursor.

Hope that helps

**Comment by mayur-mi** [comment]
Please refer this if you still believe i am not clear about my thoughts. :)

**Comment by mayur-mi** [comment]
Thanks. I now am starting to get the idea behind ORMs.
