### ISSUE TITLE
Error:(27, 13) Failed to resolve: co.uk.rushorm:rushandroid:1.2.0

### ISSUE THREAD

**Issue by phuongphally** [Stuart-campbell/RushOrm#125]

**Comment by Stuart-campbell** [comment]
repositories {
   maven {
       url "http://maven.rushorm.com"
   }
}

**Comment by phuongphally** [comment]
@ Stuart-campbell thanks

**Comment by Stuart-campbell** [comment]
The repo is now on maven central and soon to be jcentral so the custom maven repo will no longer be needed. About time I got that sorted!!
