### ISSUE TITLE
Retrieved escaped values from database

### ISSUE THREAD

**Issue by mladenbabic** [Stuart-campbell/RushOrm#126]
Hi,

My Rush object stored with some string values with characters <  and >,  but after retrieving the object from the DB, the object contains escaped values like this &lt;. How can I prevent escaping string values? Can I override the class AndroidRushStringSanitizer which probably does escape?

**Comment by Stuart-campbell** [comment]
Hi,

Yes you can do exactly that. Create a new class that implements RushStringSanitizer. Then set it on the AndroidInitializeConfig via setRushStringSanitizer. Then all strings will use that class before going into the db.

Thanks

**Comment by mladenbabic** [comment]
Hi Stuart,

Tnx a lot for quick response. I'll do it that way.
