### ISSUE TITLE
Possibility to override Rush Object ID?

### ISSUE THREAD

**Issue by mladenbabic** [Stuart-campbell/RushOrm#127]
Hi, 
I need to override rush id so that I can retrieve data from the server as JSON and converted it as an object, but I don't want to check every time if a similar object exists in rush db. Any chance to override rush id, so in that case, db will make update and  not create a new record?

Tnx in advance.
Kind regards,
Mladen

**Comment by mladenbabic** [comment]
Ok, I've found a solution with this RushCore.getInstance().registerObjectWithId() method.
Is this a right way?

Tnx.

**Comment by Stuart-campbell** [comment]
Hi,

Yes that will do it make sure you call that before saving the newly created object.

Thanks

**Comment by mladenbabic** [comment]
With RushCore.getInstance().registerObjectWithId() now I'm getting this error:
`android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: rush_some_object.rush_id`. What that means?  I guessed that with RushCore.getInstance().registerObjectWithId() will avoid conflicts.

**Comment by Stuart-campbell** [comment]
Could you have set one of the IDs to null?

**Comment by mladenbabic** [comment]
Fixed. Tnx
