### ISSUE TITLE
meta tags required

### ISSUE THREAD

**Issue by RasmusKOlsen** [Stuart-campbell/RushOrm#13]
(copy from https://github.com/Stuart-campbell/RushCore/issues/1 - looks like i managed to post in a wrong repo)

Hi.

I found what seems to be either a documentation or an implementation error.

The meta tags seems to be required in the android manifest, or a null pointer is thrown:

    
    <meta-data android:name="Rush_db_name" android:value="poly.danalock.db" />

    
    <meta-data android:name="Rush_debug" android:value="false" />

    
    <meta-data android:name="Rush_requires_table_annotation" android:value="false" />
The error seems to happen in AndroidRushConfig.java line 32 - it is expected that meta tags are defined within the application.

For clarity it might also be worth changing the documentation regarding these meta tags to make it clear that they should be childs of theapplication tag.

**Comment by Stuart-campbell** [comment]
Hi,

Thanks for reposting.

Yeah you are correct they need to be in the application tag. I will add a side note in the docs to make that clear.

Are you actually getting a null pointer if they are not included? All the meta-data tags should have default fall backs if not specified.

Thanks

**Comment by RasmusKOlsen** [comment]
yes, if I do not include them I get a null pointer.

From a quick glance at the code it seems to be AndroidRushConfig.java at line 32, part of my stacktrace:
 Caused by: java.lang.NullPointerException
            at co.uk.rushorm.android.AndroidRushConfig.<init>(AndroidRushConfig.java:32)
            at co.uk.rushorm.android.RushAndroid.initialize(RushAndroid.java:29)
            at co.uk.rushorm.android.RushAndroid.initialize(RushAndroid.java:23)
            ....MainApplication.onCreate(MainApplication.java:19)

So it happens before there is a chance for the default values be assinged.
For the record I tested it on android 4.4 using genymotion.

**Comment by Stuart-campbell** [comment]
Sounds like bundle is null at this point.

    ApplicationInfo ai = context.getPackageManager().getApplicationInfo(context.getPackageName(), PackageManager.GET_META_DATA);
    Bundle bundle = ai.metaData;

Ill put a null check in. 

Thanks

**Comment by Stuart-campbell** [comment]
Hi, Sorry I was a bit slow on this one. Resolved now.

Cheers
