### ISSUE TITLE
can't delete objects

### ISSUE THREAD

**Issue by zean** [Stuart-campbell/RushOrm#14]
Hi there, i ca't delete objects the code i use for it is this one

        List<Phone_Contact> phone_contacts = new RushSearch().find(Phone_Contact.class);
        RushCore.getInstance().delete(phone_contacts, new RushCallback() {
            @Override
            public void complete() {
                Log.e(TAG, "phone contacts completed");
                List<Phone_Contact> phone_contacts = new RushSearch().find(Phone_Contact.class);
                Log.e(TAG, phone_contacts.toString());
            }
        });

tried also like this 
        List<Chat_Object> chats = new RushSearch().find(Chat_Object.class);
        for (Chat_Object obj : chats) {
            obj.delete(new RushCallback() {
                @Override
                public void complete() {
                    Log.e(TAG, "chats completed");
                }
            });
        }

for the saving part i'm doing it like this
Chat_Object newChat = new Chat_Object();
                newChat.setUsers(String.valueOf(chats.size()), me_user, other_user);
                newChat.save();

in any case they're not deleted, can you help me with that?

**Comment by Stuart-campbell** [comment]
Hi, thanks for reporting.

Can you share Phone_Contact class and the Chat_Object class.

Also could you add

        <meta-data android:name="Rush_debug" android:value="true" />
        <meta-data android:name="Rush_log" android:value="true" />

to your application in the manifest will hopefully provide some useful logging. 

Thanks

**Comment by zean** [comment]
Quick reply, nice :+1: 

in the manifest i set, no log though

        <meta-data
            android:name="Rush_db_version"
            android:value="2" />
        <meta-data
            android:name="Rush_db_name"
            android:value="chats.db" />

        <meta-data
            android:name="Rush_debug"
            android:value="true" />

        <meta-data
            android:name="Rush_log"
            android:value="true" />

        <meta-data
            android:name="Rush_requires_table_annotation"
            android:value="false" />


public class Chat_Object extends RushObject {

    private String chat_id;
    private Chat_User friend;
    private Chat_User me;
    @RushList(classType = Chat_Msg.class)
    private List<Chat_Msg> chat_msgs;

    public Chat_Object(String chat_id, Chat_User friend, Chat_User me, List<Chat_Msg> chat_msgs) {
        this.chat_id = chat_id;
        this.friend = friend;
        this.me = me;
        this.chat_msgs = chat_msgs;
    }


    public Chat_Object() {
        chat_msgs = new ArrayList<>();
    }

    public Chat_User getFriend() {
        return friend;
    }

    public void setFriend(Chat_User friend) {
        this.friend = friend;
    }

    public Chat_User getMe() {
        return me;
    }

    public void setMe(Chat_User me) {
        this.me = me;
    }

    public String getChat_id() {
        return chat_id;
    }

    public void setChat_id(String chat_id) {
        this.chat_id = chat_id;
    }

    public List<Chat_Msg> getChat_msgs() {
        return chat_msgs;
    }

    public void setChat_msgs(List<Chat_Msg> chat_msgs) {
        this.chat_msgs = chat_msgs;
    }

    public void setUsers(String chat_id, Chat_User me, Chat_User friend) {
        this.chat_id = chat_id;
        this.me = me;
        this.friend = friend;
        this.chat_msgs = new ArrayList<>();
    }

    @Override
    public String toString() {
        return "Chat_Object{" +
                "chat_id='" + chat_id + '\'' +
                ", friend=" + friend.toString() +
                ", me=" + me.toString() +
                ", chat_msgs=" + chat_msgs.toString() +
                '}';
    }

    public void addMessage(String msg, long time, int type) {
        chat_msgs.add(new Chat_Msg(String.valueOf(chat_msgs.size()), msg, time, type));
    }
}

    public Chat_Msg(String chat_id, String text, long timestamp, int type) {
        this.chat_id = chat_id;
        this.text = text;
        this.timestamp = timestamp;
        this.type = type;
        this.read = false;
        this.locked = true;
    }

    public Chat_Msg() {
    }

    public String getText() {
        return text;
    }

    public void setText(String text) {
        this.text = text;
    }

    public long getTimestamp() {
        return timestamp;
    }

    public void setTimestamp(long timestamp) {
        this.timestamp = timestamp;
    }

    public int getType() {
        return type;
    }

    public void setType(int type) {
        this.type = type;
    }

    public String getChat_id() {
        return chat_id;
    }

    public void setChat_id(String chat_id) {
        this.chat_id = chat_id;
    }

    public boolean isRead() {
        return read;
    }

    public void setRead(boolean read) {
        this.read = read;
    }

    public boolean isLocked() {
        return locked;
    }

    public void setLocked(boolean locked) {
        this.locked = locked;
    }

    @Override
    public String toString() {
        return "Chat_Msg{" +
                "chat_id='" + chat_id + '\'' +
                ", text='" + text + '\'' +
                ", timestamp=" + timestamp +
                ", type=" + type +
                ", read=" + read +
                ", locked=" + locked +
                '}';
    }


public class Phone_Contact extends RushObject {


    private String id;
    private String name;
    private String phone_number;
    private String image_url;

    public Phone_Contact(String id, String name, String phone_number, String image_url) {
        this.id = id;
        this.name = name;
        this.phone_number = phone_number;
        this.image_url = image_url;
    }

    public Phone_Contact() {
    }


    public String getId() {
        return id;
    }

    public String getName() {
        return name;
    }

    public String getPhone_number() {
        return phone_number;
    }

    public String getImage_url() {
        return image_url;
    }

    @Override
    public String toString() {
        return "Phone_Contact{" +
                "id='" + id + '\'' +
                ", name='" + name + '\'' +
                ", phone_number='" + phone_number + '\'' +
                ", image_url='" + image_url + '\'' +
                '}';
    }
}

**Comment by Stuart-campbell** [comment]
Without fulling testing this. On first look you seem to Override 

    getId()

in Phone_Contact which could well be the source of the problem.

**Comment by zean** [comment]
Exactly!!! missed that, btw maybe you could change the "id" field to something like "rush_id" or similar since many jsons come with a id or _id field.

Txs :+1:

**Comment by Stuart-campbell** [comment]
The id rush uses is saved in the database as "rudh_id", so wouldn't clash in the database with your id field. Just the getter is named getId().

So you don't need to change your field name just getId();

Thanks glad to help.
