### ISSUE TITLE
RushORM crashed with AnnotationCache.getFieldToIgnore() on a null object reference

### ISSUE THREAD

**Issue by wilson1on1pk** [Stuart-campbell/RushOrm#15]
Hi, when i using _RushOrm_ to save some files (include TextFile and Bitmap), the app crashed with null object reference on  AnnotationCache.getFieldToIgnore() . But _RushOrm_ are working correctly with normal object which extends _RushObject_:

---

03-23 19:51:25.295: E/AndroidRuntime(6773): FATAL EXCEPTION: main
03-23 19:51:25.295: E/AndroidRuntime(6773): Process: im.maka.mapp, PID: 6773
03-23 19:51:25.295: E/AndroidRuntime(6773): java.lang.NullPointerException: Attempt to invoke interface method 'java.util.List co.uk.rushorm.core.AnnotationCache.getFieldToIgnore()' on a null object reference
03-23 19:51:25.295: E/AndroidRuntime(6773): 	at co.uk.rushorm.core.implementation.ReflectionSaveStatementGenerator.generateSaveOrUpdate(ReflectionSaveStatementGenerator.java:107)
03-23 19:51:25.295: E/AndroidRuntime(6773): 	at co.uk.rushorm.core.implementation.ReflectionSaveStatementGenerator.generateSaveOrUpdate(ReflectionSaveStatementGenerator.java:73)
03-23 19:51:25.295: E/AndroidRuntime(6773): 	at co.uk.rushorm.core.RushCore.save(RushCore.java:376)
03-23 19:51:25.295: E/AndroidRuntime(6773): 	at co.uk.rushorm.core.RushCore.save(RushCore.java:134)
03-23 19:51:25.295: E/AndroidRuntime(6773): 	at co.uk.rushorm.core.RushCore.save(RushCore.java:129)
03-23 19:51:25.295: E/AndroidRuntime(6773): 	at co.uk.rushorm.core.RushObject.save(RushObject.java:12)
03-23 19:51:25.295: E/AndroidRuntime(6773): 	at co.uk.rushorm.core.RushFile.writeToFile(RushFile.java:41)
03-23 19:51:25.295: E/AndroidRuntime(6773): 	at co.uk.rushorm.core.RushTextFile.setText(RushTextFile.java:28)
03-23 19:51:25.295: E/AndroidRuntime(6773): 	at im.maka.mapp.editor.Editor.Save(Editor.java:536)

---

BTW: I change a little bit of the code which you mentioned quick fix at https://github.com/Stuart-campbell/RushOrm/issues/4 , is it the reason of the exception? Thanks a lot!

**Comment by Stuart-campbell** [comment]
Hi,

Have you created your own implementation of the RushClassFinder?

Thanks

**Comment by wilson1on1pk** [comment]
Oh! 
That is the problem, thanks a lot! now it works perfectly! 
Thank you very much!
