### ISSUE TITLE
Storing arrays not working

### ISSUE THREAD

**Issue by nis73** [Stuart-campbell/RushOrm#16]
Hi, I'm trying to store a simple integer array to the database but it seems not to work. When I reload the same object from database, the array is `null`. Please see the minimal example:

    public class TestObject extends RushObject {

        private int[] mArray;

        public TestObject() {
        }

        public int[] getArray() {
            return mArray;
        }

        public void setArray(int[] mArray) {
            this.mArray = mArray;
        }
    }

And here's my Activity:

    public class MainActivity extends ActionBarActivity {

        @Override
        protected void onCreate(Bundle savedInstanceState) {
            super.onCreate(savedInstanceState);
            setContentView(R.layout.activity_main);

            TestObject object = new TestObject();
            object.setArray(new int[]{1, 2, 3, 4, 5});
            object.save();

            List<TestObject> testObjects = new RushSearch().find(TestObject.class);
            System.out.println(Arrays.toString(testObjects.get(0).getArray()));
        }
    }

Do I need to handle arrays in a special manner or is it not possible to use arrays?

**Comment by Stuart-campbell** [comment]
Hi,

They are currently unsupported. Simple reason I have don't don't it yet is because the size may be very large so not clear what type the sql column should be.

It should be pretty easy to write you own RushColumn so that it can save. I have not tested/finished the code snippet below, but that is the basic idea.

    List<RushColumn> columns = new ArrayList<>();
    columns.add(new IntArrayColumn());

    RushAndroid.initialize(getContext().getApplicationContext(), columns);
              	
    /* Below is an example of creating a custom field */          	
    public class MyClass {
        public String name;
    }
              	
    private class IntArrayColumn implements RushColumn<int[]> {
        @Override
        public String sqlColumnType() {
            return "varchar(255)";
        }

        @Override
        public String serialize(int[] object, RushStringSanitizer stringSanitizer) {
// TODO turn into string
            return string
        }

        @Override
        public MyClass deserialize(String value) {
// TODO turn back into array
            return int[];
        }

        @Override
        public Class[] classesColumnSupports() {
            return new Class[]{int[].class};
        }
    }

**Comment by nis73** [comment]
Thanks a lot. I'm going to try it later this evening and will let you know if it works.

**Comment by nis73** [comment]
I got it working with your suggestion. Here's my code. Maybe it helps someone else.

    public class IntArrayColumn implements RushColumn<int[]> {

        private static final String DELIMITER = ",";

        @Override
        public String sqlColumnType() {
            return "varchar(255)";
        }

        @Override
        public String serialize(int[] ints, RushStringSanitizer rushStringSanitizer) {
            return rushStringSanitizer.sanitize(join(ints));
        }

        @Override
        public int[] deserialize(String s) {
            return split(s);
        }

        @Override
        public Class[] classesColumnSupports() {
            return new Class[]{int[].class};
        }

        private String join(int[] ints) {
            if (ints.length > 0) {
                StringBuilder sbuild = new StringBuilder();
                for (int i = 0; i < ints.length; i++) {
                    sbuild.append(ints[i]).append(DELIMITER);
                }
                sbuild.delete(sbuild.lastIndexOf(DELIMITER), sbuild.length());
                return sbuild.toString();
            } else {
                return "";
            }
        }

        private int[] split(String source) {
            if (source != null) {
                if (source.isEmpty()) {
                    return new int[0];
                }
                String[] items = source.split(DELIMITER);
                int[] ints = new int[items.length];
                for (int i = 0; i < ints.length; i++) {
                    ints[i] = Integer.valueOf(items[i]);
                }
                return ints;
            }
            return null;
        }
    }
