### ISSUE TITLE
Jar inclusion results in "Error:Execution failed for task ':app:dexDebug'"

### ISSUE THREAD

**Issue by nooruls143** [Stuart-campbell/RushOrm#2]
Hi,
I am trying to use this lib and included the JAR in android project but it gives the following error:
"Error:Execution failed for task ':app:dexDebug'"

Can you please check this issue.

Thanks,
Noorul

**Comment by Stuart-campbell** [comment]
Hi,

Would you be able to share your gradle file?

Thanks

**Comment by nooruls143** [comment]
Hi Stuart,

    buildscript {
        repositories {
            maven { url 'https://maven.fabric.io/public' }
        }
    
        dependencies {
            classpath 'io.fabric.tools:gradle:1.+'
        }
    }
    apply plugin: 'com.android.application'
    apply plugin: 'io.fabric'
    apply plugin: 'idea'
    
    
    repositories {
        maven { url 'https://maven.fabric.io/public' }
    }
    
    
    android {
        compileSdkVersion 21
        buildToolsVersion '21.1.1'
        defaultConfig {
            applicationId 'com.rayat.pricewiz'
            minSdkVersion 17
            targetSdkVersion 21
            versionCode 1
            versionName '1.0'
        }
        buildTypes {
            release {
                minifyEnabled false
                proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            }
        }
        productFlavors {
        }
    }
    
    android {
        packagingOptions {
            exclude 'META-INF/notice.txt'
            exclude 'META-INF/LICENSE.txt'
            exclude 'META-INF/license.txt'
            exclude 'META-INF/NOTICE.txt'
        }
    }
    
    dependencies {
        compile fileTree(include: ['*.jar'], dir: 'libs')
        compile files('libs/androidmvcframework.jar')
        compile files('libs/ksoap2-android-assembly-2.5.8-jar-with-dependencies.jar')
        compile files('libs/universal-image-loader-1.9.2.jar')
        // You must install or update the Google Repository through the SDK manager to use this dependency.
        // You must install or update the Google Repository through the SDK manager to use this dependency.
        compile 'com.google.android.gms:play-services:6.1.71'
        compile 'com.android.support:recyclerview-v7:+'
        compile files('libs/CWAC-SackOfViewsAdapter.jar')
        compile 'com.daimajia.swipelayout:library:1.1.7@aar'
        compile 'com.octo.android.robospice:robospice:1.4.14'
        compile 'com.octo.android.robospice:robospice-spring-android:1.4.14'
        compile 'com.facebook.android:facebook-android-sdk:3.21.1'
        compile('com.twitter.sdk.android:twitter:1.1.1@aar') {
            transitive = true;
        }
        compile files('libs/javax.mail-1.4.5.jar')
        compile files('libs/javax.mail.jar')
        compile files('libs/jackson-databind-2.5.0.jar')
        compile files('libs/jackson-all-1.9.11.jar')
        compile files('libs/jackson-mini-1.9.11.jar')
        compile files('libs/rushandroid-0.5.0.jar')
    }

Thanks,
Noorul

**Comment by Stuart-campbell** [comment]
Can you confirm the problem is solved when compile files('libs/rushandroid-0.5.0.jar') is commented out?

**Comment by nooruls143** [comment]
Hi
yes if I comment rush android it compiles successfully.

**Comment by Stuart-campbell** [comment]
As you have "compile fileTree(include: ['*.jar'], dir: 'libs')" even with rush android commented out it should still be included.

With "compile files('libs/rushandroid-0.5.0.jar')" commented out can you call "RushAndroid.initialize(getApplicationContext());"

The error looks like the same package is included twice with different methods in them. Which is odd as Rush includes no other jars.

**Comment by nooruls143** [comment]
Thanks Stuart,
The multiple reference of the Rush jar with "compile fileTree" and "compile files" caused the error. I commented out the "fileTree" reference and it is working now.
