### ISSUE TITLE
How to set ID?

### ISSUE THREAD

**Issue by HDANILO** [Stuart-campbell/RushOrm#21]
I can see a getID method, but I want to set ID prior to saving, its important because the local DB must have the same ID's as the server, so, server generates them, not the local DB.

**Comment by dco5** [comment]
You can use the property ID from the server if you need to, I think rushorm uses rush_id, so if you want to set the id from server just use the setId(int serverId) and to get it you have to use something like getServerID() because getId returns rush_id. I had that same question when I was doing my app but I had no problem at all using the serverId. That is why I started using RushOrm, i was trying with SugarORM and it was a big conflict because you can not use the property ID, unlike with RushORM.

**Comment by HDANILO** [comment]
@dco5 Same problem, just tossed Sugar out, trying Rush, seems promising, but, what if I use some one-to-many relation? Can I force Rush to make those relations based on my serverID in a simple way?

**Comment by dco5** [comment]
I had one-to-many relation too, with no problems at all. I never search for the children directly, but if you have to search directly for them you can put the parent  server id, and search for the children with parent server id

**Comment by HDANILO** [comment]
I'm using @RushList to do the one-to-many, they'll automatically use the rush_id which is private, am I right? This will reflect too, because the "children" are also persisted on the server and they should not carry the rush_id or a fk related to rush_id.

**Comment by HDANILO** [comment]
Done some analising, seems like its a matter of adding getID on RushMetaData and the getID on the RushCore, and reflect that also on RushObject and Rush interface.

**Comment by Stuart-campbell** [comment]
Have you has a look at

 RushCore.getInstance().deserialize();

It is dependent on your sever giving you your data in json format that matches your java objects, but you can pass in the name of the id field in the json the it will be used in the database instead of creating it's own id. Might be what your looking for.

**Comment by Stuart-campbell** [comment]
Also searching for children is now possible with 

    RushSearch.whereChildOf(Rush parent, Sting field);

Thanks

**Comment by HDANILO** [comment]
@Stuart-campbell To create the object with proper ID I must give a JSON to be deserialized? Dont you think its a work around, and those are bad some times? my server already uses its protocol to comunicate with the application, and I really dont want to change that. 

If you want, I can do a pull request fixing the setID, making my life, and I bet, many other people life better, ofc, if there isnt a problem with that!

I bet the search children uses the rush_id to go through the children, and thats exactly what I must avoid if I follow the suggestion from @dco5 and create my own ID, since at any time, the local DB can be wiped, and sync'ed again from the server, this will for sure mess things up. It could be better, if I could edit it with setID that could be even easier because all would work without the need of putting extra fields(IDs) and making the one to many relation myself hard coded

**Comment by Stuart-campbell** [comment]
No I wouldn't suggest turning into json just to set the id. Was pointing it out as you may have already been deserializing with something like gson so would have been an easy switch.

I think I do understand your use case. Basically you need what the deserialize method does but without using it.

The rush_id is really a "final" property so I think adding a registerObjectWithId method might make more sense than setId.

Although if I add that to RushCore it would be easy for you to add setId to your object that would just call that method.

I should be able to look at that tomorrow.

Thanks

**Comment by HDANILO** [comment]
@Stuart-campbell Thank you very much, that registerObjectWithId would work too!

**Comment by Stuart-campbell** [comment]
Hi,

I have added registerObjectWithId method. So if you call that after creating your objects from your server calling save will create or updated them based on the id you set.

https://github.com/Stuart-campbell/RushCore/blob/master/src/main/java/co/uk/rushorm/core/RushCore.java#L341-348

Cheers

**Comment by Stuart-campbell** [comment]
Added in v1.1.3
