### ISSUE TITLE
Unfortunate comment

### ISSUE THREAD

**Issue by HDANILO** [Stuart-campbell/RushOrm#22]
https://github.com/Stuart-campbell/RushOrm/blob/master/RushORM/app/src/main/java/co/uk/rushexample/Demo/Car.java#L22

I guess you meant RushORM

**Comment by Stuart-campbell** [comment]
Woops. Thats a reminisce from a demo I wrote comparing, Sugar, ActiveAndroid and Ormlite. Best update it.
