### ISSUE TITLE
How to access rush_created and rush_updated fields?

### ISSUE THREAD

**Issue by fabsimilian** [Stuart-campbell/RushOrm#24]
The database fields rush_created und rush_updated are created automatically. How can I access them from a RuhsObject?

**Comment by Stuart-campbell** [comment]
I think I intended to add this to the base object but it seems to have slipped by.
    
    RushCore.getInstance().getMetaData(yourObject).getCreated();

It returns updated and created as a long so you will just have to create a new Date with the value.

Thanks

**Comment by fabsimilian** [comment]
Works fine! Thank you!
