### ISSUE TITLE
Same RushSearch in different activities => not the same results

### ISSUE THREAD

**Issue by PaulineBAUDOUIN** [Stuart-campbell/RushOrm#25]
Hi, I'm trying to make :
```
List<Maquette> temp = new RushSearch().find(Maquette.class);
System.out.println(temp.size());
```
from two different activities but they don't display the same thing:
- the **MainActivity** from which I create and save my two Maquette objects **displays 2** (ok)
- the **MaquetteActivity** from which I would like to get all my Maquettes to display them in a ListView **displays 0**

I don't understand why... Could you help me ?

**Comment by PaulineBAUDOUIN** [comment]
I also have the Error:
```
A SQLiteConnection object for database '+data+data+mypackage+databases+android_db' was leaked!  
Please fix your application to end transactions in progress properly and to close the database when it is no longer needed.
``` 
Is it linked ?

**Comment by Stuart-campbell** [comment]
From a quick look, I think this may be a bug introduced in the last release.

If you downgrade to v1.1.2 it should be ok. I will get a fix out asap.

Looks like an unbalanced call to start and stop transaction.

Thanks

**Comment by PaulineBAUDOUIN** [comment]
Thanks for answering so quickly ! 
How can I downgrade please ? Is it in the Manifest ?

**Comment by Stuart-campbell** [comment]
Just in your gradle file  

    dependencies {
            compile 'co.uk.rushorm:rushandroid:1.1.2'
    }
	

Or download the 1.1.2 jar from here http://www.rushorm.com/download.html

**Comment by PaulineBAUDOUIN** [comment]
I am already in 1.1.2 actually ! 
I use the package named rushandroid-1.1.2.jar

**Comment by Stuart-campbell** [comment]
Might need a bit more info. I guess its worth upgrade to 1.1.3 then. If you do two loads in a row does it work?

Are you able to share the Maquette class?

**Comment by PaulineBAUDOUIN** [comment]
Ok I'll upgrade to 1.1.3. Here is my onCreate from my MaquetteActivity class:
``` Java
protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        RushAndroid.initialize(getApplicationContext());
        setContentView(R.layout.activity_maquette_images);

        android.support.v7.app.ActionBar ab = getSupportActionBar();
        selected = null;

        List<Gabarit> temp2 = new RushSearch().find(Gabarit.class);

        for(int i = 0; i < temp2.size(); i++){
            names[i] = temp.get(i).nom
        }

        // get the custom layout for action bar
        LayoutInflater li = LayoutInflater.from(this);
        View customView = li.inflate(R.layout.custom_action_bar, null);

        // asset values to textView, imageView from the custom layout for action bar
        TextView tv = (TextView)(customView.findViewById(R.id.title));
        tv.setText("Maquettes");

        ImageView imgLeft = (ImageView)(customView.findViewById(R.id.imgLeft));
        imgLeft.setImageResource(R.drawable.arrow_left);

        ImageView imgRight = (ImageView)(customView.findViewById(R.id.imgRight));
        imgRight.setImageResource(R.drawable.done);
        imgRight.setOnClickListener(imgRightListener);

        // create the link between custom layout and the action bar
        ab.setCustomView(customView);
        ab.setDisplayShowCustomEnabled(true);

        vignettes = (ListView)(findViewById(R.id.vignettes)); // ok
        System.out.println("NAMES NULL " + (names == null));
        VignetteListAdapter vignetteAdapter = new VignetteListAdapter(this, names);
        vignettes.setAdapter(vignetteAdapter);

        text = (TextView)(findViewById(R.id.textView));
        editText = (EditText)(findViewById(R.id.nomProjet));

        vignettes.setOnItemClickListener(vignetteListener);

    }
```

**Comment by Stuart-campbell** [comment]
Your problem may be be caused by calling

     RushAndroid.initialize(getApplicationContext());

in your activity. You need to make sure this is called in a singleton. Standard way to do this is to create a custom Application class and call it there.

    public class MyApplication extends Application {

    @Override
    public void onCreate() {
        super.onCreate();
         RushAndroid.initialize(getApplicationContext());
    }
    }

Just need to make sure that you set the name of the application in your manifest.

    <application
            android:name="{package}.MyApplication"
     >
            ...
    </application>

Cheers

**Comment by PaulineBAUDOUIN** [comment]
Thanks for your answer but it doesn't work... 
```
List<Maquette> temp = new RushSearch().find(Maquette.class);
System.out.println(temp.size());
```
still displays 0

**Comment by Stuart-campbell** [comment]
Can you share the Maquette class than extends RushObject?

**Comment by PaulineBAUDOUIN** [comment]
Here it is :
``` java
public class Maquette extends RushObject {
    public String descritpion;
    public int identifier;
    public int img;
    public String nom;

    public ArrayList<Gabarit> gabarits;
    public ArrayList<Order> orders;
    public ArrayList<Projet> projets;
    public ArrayList<Utilisateur> utilisateurs;

    public Maquette() {
        this.descritpion = "";
    }

    public String toString(){
        return "Maquette n°" + identifier;
    }
}
```

**Comment by Stuart-campbell** [comment]
Can you add these two metadata tags to your manifest to see if anything is logged?

    <meta-data android:name="Rush_debug" android:value="true" />
    <meta-data android:name="Rush_log" android:value="true" />

In the example code you posted above I couldn't see where you loaded the objects?

Could you run this code in one activity and tell me if your also getting 0.

new Maquette().save();
List<Maquette> objects = new RushSearch().find(Maquette.class);
System.out.println(objects.size());

**Comment by PaulineBAUDOUIN** [comment]
Yes indeed I changed my class to try to find the solution and forgot to modify it back. I just updated my comment :) 
I tried the three lines you gave me and I get an error:
04-21 15:06:44.115  17155-17168/focalys.avh_android E/AndroidRuntime﹕ FATAL EXCEPTION: Thread-1231
    Process: focalys.avh_android, PID: 17155
    android.database.sqlite.SQLiteConstraintException: PRIMARY KEY must be unique (code 19)
            at android.database.sqlite.SQLiteConnection.nativeExecuteForChangedRowCount(Native Method)
            at android.database.sqlite.SQLiteConnection.executeForChangedRowCount(SQLiteConnection.java:924)
            at android.database.sqlite.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:754)
            at android.database.sqlite.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:64)
            at android.database.sqlite.SQLiteDatabase.executeSql(SQLiteDatabase.java:1795)
            at android.database.sqlite.SQLiteDatabase.execSQL(SQLiteDatabase.java:1724)
            at co.uk.rushorm.android.AndroidRushStatementRunner.runRaw(AndroidRushStatementRunner.java:37)
            at co.uk.rushorm.core.RushCore$12.runRaw(RushCore.java:442)
            at co.uk.rushorm.core.implementation.ReflectionUpgradeManager.moveRows(ReflectionUpgradeManager.java:284)
            at co.uk.rushorm.core.implementation.ReflectionUpgradeManager.upgrade(ReflectionUpgradeManager.java:122)
            at co.uk.rushorm.core.RushCore.upgrade(RushCore.java:432)
            at co.uk.rushorm.core.RushCore.access$300(RushCore.java:39)
            at co.uk.rushorm.core.RushCore$1.run(RushCore.java:107)
            at java.lang.Thread.run(Thread.java:841)

**Comment by Stuart-campbell** [comment]
Do you have a number of objects that extend RushObject? I might be to do with changing names and types of variables while developing. While it does its best to handle that there could be a change in data structure its failing to migrate. Fully uninstalling and reinstalled may fix it. If you checking none of you objects use mysql reserved names could be something to do with it (which is on the to fix list).

https://github.com/Stuart-campbell/RushOrm/issues/20

**Comment by PaulineBAUDOUIN** [comment]
I already tried to uninstall my app, but it didn't work either...
It is as if the data base made a reference to my Maquette java objects because when I change activity (=> instances of my Maquette java objects are destroyed), the DB seems to be empty

**Comment by PaulineBAUDOUIN** [comment]
When I uninstall my app and reinstall it with the 3 lines
``` java
new Maquette().save();
        List objects = new RushSearch().find(Maquette.class);
        System.out.println(objects.size());
```
It displays 1

**Comment by Stuart-campbell** [comment]
Is it still not working one activity to another?

**Comment by PaulineBAUDOUIN** [comment]
If the saving and the RushSearch are made in the same activity, there is a result but from one activity to another it gives 0

**Comment by Stuart-campbell** [comment]
Is that error still being logged?

**Comment by PaulineBAUDOUIN** [comment]
Yes, it is:
java.lang.NullPointerException: storage == null

because the result of 
``` 
List maquettes = new RushSearch().find(Maquette.class);
```
is an empty List so when I do:
```
String[] tab;
for(int i = 0; i < maquettes.size(); i++{
    tab[i] = maquettes.get(i).nom;
}
MaquetteListAdapter maquetteAdapter = new MaquetteListAdapter(this, tab);
``` 
I don't enter the for loop so tab is null.

**Comment by Stuart-campbell** [comment]
Are you setting the size of tab?

    String[] tab = new String[maquettes.size()];

**Comment by PaulineBAUDOUIN** [comment]
No I wasn't but it doesn't change the fact that maquettes.size() = 0 instead of 2 !

**Comment by PaulineBAUDOUIN** [comment]
(Anyway, thank you very much for your help and your answering quickly !)

**Comment by Stuart-campbell** [comment]
I'll have to create a test project to check this, but if it works run in a row its very hard to understand why being in different activities would make any difference.

If you get any progress or can narrow down your bug to something I can test do let me know.

Cheers

**Comment by PaulineBAUDOUIN** [comment]
I will, 
Cheers

**Comment by PaulineBAUDOUIN** [comment]
Ok, I found where I made the mistake. It's actually very simple and I am very sorry for the time you lost on my problem:
I simply switched the creation of my database with the delete of all the previous elements which actually deleted the elements I just created...

By the way, is there a simple way to reset the database ? For the moment I only get all the elements of a class and delete them one by one, then go to the new class etc...

**Comment by Stuart-campbell** [comment]
No worries glad you got it sorted.

Currently no way to reset. You can bulk delete an array of items which will be much quicker.

    RushCore.getInstance().delete(List<Rush>);

No for loop required.

Thanks
