### ISSUE TITLE
How to execute SQL?

### ISSUE THREAD

**Issue by ppamorim** [Stuart-campbell/RushOrm#26]
Hi, I need execute a SQL to truncate my tables. Do you know any way to do this?

**Comment by Stuart-campbell** [comment]
Just wondering why you would need to do this?

What situation will delete not work for you?

**Comment by ppamorim** [comment]
I need truncate my tables, Have a method to do it?

**Comment by Stuart-campbell** [comment]
No you can not directly run sql.

**Comment by ppamorim** [comment]
Can create a it?

**Comment by Stuart-campbell** [comment]
You could create your own initialize method like the one here: https://github.com/Stuart-campbell/RushOrm/blob/master/RushORM/rushandroid/src/main/java/co/uk/rushorm/android/RushAndroid.java

Then hang onto the AndroidRushStatementRunner which would let you run raw sql.

Can you explain your use case for wanting this? If I was going to add this feature to the library I would need to know why.

**Comment by ppamorim** [comment]
I need erase the all data of a table. Like truncate.

**Comment by Stuart-campbell** [comment]
Is there are problem with doing this?

    RushCore.getInstance().delete(new RushSearch().find(Object.class));

**Comment by Stuart-campbell** [comment]
Delete all added in v1.1.4

    RushCore.getInstance().deleteAll(Object.class);

That will delete all from a table.
