### ISSUE TITLE
How to clear a table?

### ISSUE THREAD

**Issue by petersnoopy** [Stuart-campbell/RushOrm#27]
Hi, I want to know a easy way to delete all rows in a table without needing to load all data.

**Comment by Stuart-campbell** [comment]
Hi,

Data does need to be loaded before deleted. The reason for this is a children are stored through join tables. So deleting without ids would leave unused rows in the join tables.

I do see that this is not a problem if you are deleting all rows so could be worth adding a clear all method.

Loading rows is pretty quick unless your taking about multiple thousands.

It can be done on a background thread.

    new RushSearch().find(Object.class, new RushSearchCallback<Object>() {
            @Override
            public void complete(List<Object> list) {
                RushCore.getInstance().delete(list, null);
            }
        });

**Comment by Stuart-campbell** [comment]
Delete all added in v1.1.4

    RushCore.getInstance().deleteAll(Object.class);

That will delete all from a table, will be far more efficient that the method above.

Thanks
