### ISSUE TITLE
Delete only one RushObject

### ISSUE THREAD

**Issue by PaulineBAUDOUIN** [Stuart-campbell/RushOrm#28]
Hi, there is something I don't understand: I have one RushObject called Utilisateur which has a list of Maquettes (also RushObject). When I do:
``` Java
Utilisateur myUser = new Utilisateur();
Maquette m1 = new Maquette();
Maquette m2 = new Maquette();
myUser.maquettes.add(m1);
myUser.maquettes.add(m2);
m1.user = myUser;
m2.user = myUser;
myUser.save();
m1.save();
m2.save();
myUser.delete();
```
it deletes myUser but also my two Maquettes m1 and m2.
Is that normal ? How could I just delete myUser without the Maquettes ?

**Comment by Stuart-campbell** [comment]
Hi,

Quick fix add this annotation to your list.

    @RushDisableAutodelete

Thanks
Stuart

**Comment by PaulineBAUDOUIN** [comment]
Thank you very much !
