### ISSUE TITLE
Customizable table name

### ISSUE THREAD

**Issue by gcalaprice** [Stuart-campbell/RushOrm#31]
Hi, as discussed via Twitter, I need to customize the name of a mapped table. For example, if I create a new RushObject child class "Book", the related table has the name of the class to which it refers (Book). This need is determined by design specification of the app. It would be nice if I can customize the table name via an annotation on the class (e.g. @RushTableName("MyCustomTableName") ).  Thanks in advance.

**Comment by Stuart-campbell** [comment]
Hi,

There is already an annotation for setting the class serialization name 

    @RushClassSerializationName

My plan in v1.1.4 is to add an optional manifest metadata tag which would mean the name provided there would also be used as the table name.

**Comment by gcalaprice** [comment]
Hi,
what is the correct use of this annotation? I tried @RushClassSerializationName(name = "NewLogEvent") because my table should be named "NewLogEvent", but logging the SQL I got this CREATE TABLE rush_<package_name>_<class_name>_BikeLog. The class name refers to the class that extends RushObject.

@RushTableAnnotation
@RushClassSerializationName(name = "NewLogEvent")
public class ClassName extends RushObject {...}

Thanks!

**Comment by Stuart-campbell** [comment]
Hi,

Not actually implemented it yet. Thats the idea of how it will work. Hope to do a new release with it in tomorrow.

Thanks

**Comment by Stuart-campbell** [comment]
I have added this in v1.1.4. Changed my mind about using @RushClassSerializationName as you might want that to differ from database name. Not sure why but no point restricting.

Add

    @RushCustomTableName(name = "MyCustomName")

to your class.

Thanks
