### ISSUE TITLE
How to delete/drop/empty whole database

### ISSUE THREAD

**Issue by fabsimilian** [Stuart-campbell/RushOrm#32]
Is it possible to drop / delete  or empty all database entries?
Or drop and recreate the database?

**Comment by Stuart-campbell** [comment]
Not yet, I am working on it should have the added soon.

**Comment by Stuart-campbell** [comment]
Added in v1.1.4

    RushCore.getInstance().clearDatabase();

That just deletes all the data in every table. If you actually want to delete it from disk you will need to use default Android way of deleting a database.

Thanks
