### ISSUE TITLE
Gradle dependency is not working

### ISSUE THREAD

**Issue by DannyLamarti** [Stuart-campbell/RushOrm#33]
Hi!,

When I add the Gradle dependency to the build.gradle file of my android app, the app will not build. Here is how I added the dependency:

dependencies {
    compile 'co.uk.rushorm:rushandroid:1.1.4'
}

And this is the response from de Gradle console:

Executing tasks: [clean, :app:compileDebugSources, :app:compileDebugTestSources]

Configuration on demand is an incubating feature.

FAILURE: Build failed with an exception.

What went wrong:
A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugCompile'.
   > Could not find co.uk.rushorm:rushandroid:1.1.4.
     Searched in the following locations:
         https://jcenter.bintray.com/co/uk/rushorm/rushandroid/1.1.4/rushandroid-1.1.4.pom
         https://jcenter.bintray.com/co/uk/rushorm/rushandroid/1.1.4/rushandroid-1.1.4.jar
         file:/C:/Program Files/Android/sdk/extras/android/m2repository/co/uk/rushorm/rushandroid/1.1.4/rushandroid-1.1.4.pom
         file:/C:/Program Files/Android/sdk/extras/android/m2repository/co/uk/rushorm/rushandroid/1.1.4/rushandroid-1.1.4.jar
         file:/C:/Program Files/Android/sdk/extras/google/m2repository/co/uk/rushorm/rushandroid/1.1.4/rushandroid-1.1.4.pom
         file:/C:/Program Files/Android/sdk/extras/google/m2repository/co/uk/rushorm/rushandroid/1.1.4/rushandroid-1.1.4.jar

Luckily maven and the jar are working fine. Though it would be nice if Gradle was working too.

**Comment by Stuart-campbell** [comment]
Hi,

To use with gradle you have to add

     repositories {
        maven {
            url "http://maven.rushorm.com"
        }
    }

The jar is not on jcenter.

Thanks

**Comment by DannyLamarti** [comment]
Thx for the alternative. It is working now ;)
