### ISSUE TITLE
Search a concrete element of a RushList inside a RushObject

### ISSUE THREAD

**Issue by cjimenezpacho** [Stuart-campbell/RushOrm#36]
Hi!, thanks for the library. Is very useful for me :)
I have a question about it (that is similar Issue #12 but more concrete)

I have two RushObject: ticket (TicketDataSourceEntity) and event (EventDataSourceEntity).
One event contains many tickets and a ticket belongs to one (and only one) event.
In code:

Firstly Event RushObject:

```Java
public class EventDataSourceEntity extends RushObject {
    int eventIdentifier;
    String name;
    Date date;
    @RushList(classType = TicketDataSourceEntity.class)
    private List<TicketDataSourceEntity> tickets;

    public EventDataSourceEntity(){}

    public EventDataSourceEntity(Event event){
        this.eventIdentifier = event.getIdd();
        this.name = event.getName();
        this.date = event.getDate();
    }

/*setters and getters and some stuff
.....
*/
}
```

And Ticket RushObjectt:

```Java
public class TicketDataSourceEntity extends RushObject {

    int ticketIdentifier;
    String ownerName;
    String code;
    String description;
    TicketStatus status;
    Date readTime;

    public TicketDataSourceEntity(){}

    public TicketDataSourceEntity(Ticket ticket){
        this.ticketIdentifier = ticket.getIdd();
        this.ownerName = ticket.getOwnerName();
        this.code = ticket.getCode();
        this.description = ticket.getDescription();
        this.status = ticket.getStatus();
        this.readTime = ticket.getReadTime();

    }

/*
getters, setters, stuff goes here...
*/
}
```

If I want to get all tickets of an event I'll do this: 

```Java
EventDataSourceEntity eventDSEntity = new RushSearch()
                .whereEqual("eventIdentifier", idEvent)
                .findSingle(EventDataSourceEntity.class);

eventDSEntity.getTickets()
```
And I can iterate over tickets attribute (RushList)

But, If I want to get one ticket of an event without iterate over the list, how could I do it?
That is, something like this in SQL:
```
select tickets.* from event 
inner join tickets on event.id = ticket.idEvent 
where event.id = 7 and ticket.id = 7458
```

Getting one ticket of an event is an operation that I need to do a lot of times. Since one event could contain several hundreds of tickets (or thousands)  I don't want to get all to iterate it every time.
Is it possible to achieve this with RushOrm?

Thanks!!

**Comment by HDANILO** [comment]
Well, you could add the parentEvent attribute to the TicketDataSourceEntity and make sure parentEvent is always the event which the ticket belongs to, this way you can use the RushSearch() on the TicketDataSourceEntity setting the ticketIdentifier and parentEvent!

TicketDataSourceEntity t = new RushSearch().whereEqual("eventParent", event).whereEqual("ticketIdentifier",7458).findSingle(TicketDataSourceEntity.class);

where event is an instance of EventDataSourceEntity with the property eventIdentifier equal to 7.

**Comment by cjimenezpacho** [comment]
Thanks @HDANILO !
Adding the parent attribute to Ticket, would I need to delete my tickets RushList from Event? Or I need both of them?
Sorry I have no experience with ORMs

**Comment by HDANILO** [comment]
@cjimenezpacho I wouldn't, if you don't remove you have a classic Many-to-One relation and that way its easier to see. Also its easier to access the tickets of a given event too, but its all up to you to model your relations the way you like the most!

**Comment by Stuart-campbell** [comment]
Hi,

You could use whereChildOf only thing about this is you would have to use the rush_id not your own id field. This method should work with the above class structure.

        new RushSearch().whereChildOf(EventDataSourceEntity.class, "tickets", rush_id)
                                      .and()
                                      .whereEqual("ticketIdentifier", 7458).findSingle(TicketDataSourceEntity.class);

Also see https://github.com/Stuart-campbell/RushOrm/issues/21 for setting the rush_id so your wouldn't need your own identifier.

**Comment by HDANILO** [comment]
I wasn't aware of this method, whereChildOf, nice one, gonna change a bit my classes due to that!

**Comment by HDANILO** [comment]
@Stuart-campbell From the child point of view, is there a whereParentOf method? Some situations in my code needs the child to get the parent's id to comunicate with the server!

**Comment by Stuart-campbell** [comment]
Is this what you mean?

    Child child;
    Parent parent = new RushSearch().whereEqual("children", child).findSingle(Parent.class);
    String id = parent.getId();

**Comment by cjimenezpacho** [comment]
@Stuart-campbell thanks for the info!
I'll test everything in a few hours :)

**Comment by HDANILO** [comment]
@Stuart-campbell exactly!
