### ISSUE TITLE
Many-to-Many relation

### ISSUE THREAD

**Issue by aercanozcan** [Stuart-campbell/RushOrm#40]
Hello is there a way to implement many-to-many relation with this library? If not are you planning to support it? Thank you for great library btw.

**Comment by Stuart-campbell** [comment]
Thanks.

Are you able to provide an example of the Java classes that you want to support?

**Comment by aercanozcan** [comment]
Is it possible to achieve a relation by doing this?

class Student{
List<Clasz> classes
}

class Clasz{
List<Student> students
}

**Comment by Stuart-campbell** [comment]
That should currently work using @RushList. Although there is one reported bug with circular relationships that I have yet to resolve. So I guess its kind of supported and will be fully in the future.

Duplicated child RushObjects with circular relationships #29

Could you redesign your data to be more like?
    
    class Register {
        Clasz clasz;
        @RushList(classType=Student.class)
        List <Student>  students
    }

    class Timetable {
        Student student;
        @RushList(classType=Clasz.class)
        List <Clasz>  claszes
    }

Thanks

**Comment by aercanozcan** [comment]
Oh I see. This is legit enough for me. Thank you.
