### ISSUE TITLE
Where clause method  for query builder with a collection of data as parameter

### ISSUE THREAD

**Issue by aercanozcan** [Stuart-campbell/RushOrm#41]
It would be very cool if we were able to build queries with a collection of data as parameter since we can not use raw sql(which is very good in my opinion).

To be clear : 
```
List<String> names;
new RushSearch().whereEqual("name",names).find(Person.class);
//or
new RushSearch().whereEqual("name","jonh","locke","Friedrich" ...).find(Person.class);


```

**Comment by Stuart-campbell** [comment]
This could be done with a helper function. I will look at adding it to the api.

    List<String> names;
    RushSearch search = new RushSearch();
    for(int i = 0; i < names.size(); i ++) {
         search.whereEqual("name", names.get(i);
         if(i < names.size() - 1) {
              search.or();
         }
    }
    List<Person> people = search.find(Person.class);

**Comment by Stuart-campbell** [comment]
Closing this off because there is a limit to the number of where clauses so having an inbuilt function would not be robust and i'd rather that if someone needs to do this they are closer to that issue.
