### ISSUE TITLE
Compatibility problem with Google App Engine endpoints

### ISSUE THREAD

**Issue by csvurt** [Stuart-campbell/RushOrm#42]
I'm trying to use RushOrm together with a Google Cloud Module in Android Studio 1.2.1.1 but I'm running into a class loading error that seems to be triggered by Rush. Here's the exception output that sparks the problem:

    I/art﹕ Rejecting re-init on previously-failed class java.lang.Class<com.google.api.client.http.UriTemplate>
    E/RushOrm﹕ com.google.api.client.http.UriTemplate
    W/nalizableReferenceQueue﹕ Could not load Finalizer in its own class loader.Loading Finalizer in the current class loader instead. As a result, you will not be ableto garbage collect this class loader. To support reclaiming this class loader, eitherresolve the underlying issue, or move Google Collections to your system class path.
        java.io.FileNotFoundException: com/google/common/base/internal/Finalizer.class
        at com.google.common.base.FinalizableReferenceQueue$DecoupledLoader.getBaseUrl(FinalizableReferenceQueue.java:251)
        ....
        at java.lang.Class.forName(Class.java:308)
        at co.uk.rushorm.android.AndroidRushClassFinder.getRushClass(AndroidRushClassFinder.java:58)
        ....

At that point the ```UriTemplate``` class is "tainted" and I get a ```NoClassDefFoundException``` when the endpoint tries to use it. Everything works as expected when I remove RushOrm from the project.

I've attached a minimal project that reproduces the problem:
[RushTest.zip | uploaded via ZenHub](https://files.zenhub.io/5571d6f7b282af931c5028f4)

You won't need to run an instance of the app engine server, the connection will fail but the exception will be triggered before that point anyway. Just "Make project" and Run.

**Comment by Stuart-campbell** [comment]
Hi,

The same solutions here should work for you
https://github.com/Stuart-campbell/RushOrm/issues/4

I'll have to have a closer look at it to see if I can resolve it without the work around. The problem is it loads all the classes in your dex so the app engine sdk must list a class but not actually contain it.

Thanks

**Comment by csvurt** [comment]
Thanks for the workaround, I'll give this a shot. The app engine does some pretty mystical stuff with class loading, some of it is pulled in through gradle, some is handled behind the scenes by Android Studio and some just seems to materialize out of thin air. I'm still trying to get a handle on it.

It might be worth offering a class registration system alongside the current initializer.  So we could either let Rush scan the classes automatically or register them ourselves in cases where the automatic discovery fails. Basically just making that workaround a more official part of the interface.
