### ISSUE TITLE
Elapsed time for large data transfer

### ISSUE THREAD

**Issue by rafa0809** [Stuart-campbell/RushOrm#43]
I have an example of large data transfer (about 9000 rows). The classes that represent the data are the following:

    public class Province extends RushObject {

	private int oid;

	private String name;

	private String postalCode;

	public Province(){
		super();
	}
        //getters and setters...
    }

    public class Location extends RushObject {

	private int oid;

	private float latitude;

	private float longitude;

	private String name;

	private Province province;

	public Location(){
		super();
	}
        //getters and setters
    }

And this is the piece of code used when extracting the data:

    LogUtils.d( "Retrieving locations from Database" );
    init = System.currentTimeMillis();
    locations = new RushSearch().find(Location.class);
    long end = System.currentTimeMillis();
    LogUtils.d( "Query Time: " + (end-init) / 1000 );

Elapsed time for real devices is about 20 seconds.

Do you think maybe exists some performance problems? Or is normal so long for querying?

**Comment by Stuart-campbell** [comment]
I have done some benchmarking against some of the other ORMs and Rush outdoes ActiveAndroid and Sugar and is a very close behind ormlite. Ormlite is a far thinner wrapper on the sql so ill live with that.

I have noticed that there seems to be a bit of a slow down when hitting about 10000 rows. I recorded 4000 in 2.5 seconds but 10x that took 66 seconds. So I there should be something I can do about that.

You can do a RushSearch async with a callback to help with this. As loading that many rows is never going to be instant.

Thanks

**Comment by rafa0809** [comment]
Okey @Stuart-campbell !! Probably performance is limited by the possibilities the SQLite. This is the reason why the people of Realm.io decided create her own storage manager.

Congrats for your nice work!!

**Comment by Stuart-campbell** [comment]
Marking this as a bug, because of the speed of operations below 4000 rows there should not be an exponential increase in take taken above that number.

**Comment by Stuart-campbell** [comment]
Improvements made in v1.1.7 but from doing some reading there is only so much you can do for 50k+ datasets.

Thanks
