### ISSUE TITLE
Saving the object and his children

### ISSUE THREAD

**Issue by StulleBrot** [Stuart-campbell/RushOrm#44]
Hey,
i have a question, not really a issue. I have a object which has as one of its attributes a list of a other object.
As your documentation says, when i save the parent object the children getting saved too. Thats working all fine.
My question is. When i do the saving work in the parent object, does it call the save function of the children object to save this children? I ask because i overwrote the save function of the children. But i think it doesnt get called when i use the save of the parent? 
Its not a real problem, because i can just use the children save and do the same.
But i just wanted to asked, if its somehow possible to configure this.
If its not easy to manage or it is just not intented, i have no problems with that.
Thanks in advance. 

Because i know my description is probably not that clear i have the code:

_______________________________________________________
public class Document extends RushObject {
  private List<Picture> pics;
 ...
}

public class Picture  extends RushObject {
private String title;
    @Override
    public void save() {
        this.setTitle("MÖÖÖP");
        super.save();
    }
}
__________
And when i do the following:
Document doc = new Document();
Picture pic = new Picture("Test");
doc.addPicture(pic);
doc.save();
The title doesnt get changed.
But with pic.save() it does.

So again, thanks in advance

**Comment by Stuart-campbell** [comment]
Hi,

No saving the parent does not call save on the children. Saving children is done in a transaction, calling save on the parent starts the transaction so wouldn't work calling it on the children. I don't think any methods are called on RushObject all the methods on RushObject just call through to the Engine class.

I never really though about people wanting to do actions on save or load, could be a case for adding some callbacks. Nothing supported currently though.

Thanks

**Comment by StulleBrot** [comment]
Ok.
Thanks for the fast answer
