### ISSUE TITLE
Saving HashMap

### ISSUE THREAD

**Issue by StulleBrot** [Stuart-campbell/RushOrm#45]
Hey,

is there a easy way to store a Class that extends HashMap or just a HashMap in RushORM ?

For the first, maybe here the sample snippet:
_____________________________
@RushTableAnnotation
public class HashMapTest extends HashMap<String, String> implements Rush {
    private String key;
    private String value;

    public HashMapTest() {
    }
    
    @Override
    public void save() { RushCore.getInstance().save(this); }
    @Override
    public void save(RushCallback callback) { RushCore.getInstance().save(this, callback); }
    @Override
    public void delete() { RushCore.getInstance().delete(this); }
    @Override
    public void delete(RushCallback callback) { RushCore.getInstance().delete(this, callback); }
    @Override
    public String getId() { return RushCore.getInstance().getId(this); }
}
____________________________________________
Thanks in advance again.

**Comment by Stuart-campbell** [comment]
Hi,

No Maps are not supported something I have thought about for the future but no plans of doing it soon.

Apart from the look up ability of a Map you could do this.

    class ClassA {
        @RushList(className = ClassB.class
        List<ClassB> classB;
    } 

    class ClassB {
        ClassC classC;
        ClassD classD;
    }

where ClassC and ClassD are what you needed to store in a map.
Note: All must extend RushObject or implement Rush

Thanks
