### ISSUE TITLE
Your website / the maven repo is down. 

### ISSUE THREAD

**Issue by fabsimilian** [Stuart-campbell/RushOrm#46]
So we are not able to build the project with gradle. :)

**Comment by Stuart-campbell** [comment]
Oh dear, uploading to maven central I think is now at the top of the TODO list.

I just upload the latest jar to https://gitter.im/Stuart-campbell/RushOrm as not to stop your development while I fix the server.

Sorry about that.

**Comment by Stuart-campbell** [comment]
Website is finally back up.

Thanks
