### ISSUE TITLE
Support for SQL "LIKE"

### ISSUE THREAD

**Issue by UnknownJoe796** [Stuart-campbell/RushOrm#47]
I need to search through a bunch of text columns, and I haven't found any function that does it, so I'm guessing it's not implemented yet.

**Comment by Stuart-campbell** [comment]
Sounds like a worthwhile feature. Should be able to add in the next few weeks.

**Comment by Stuart-campbell** [comment]
RushSearch.whereStartsWith
RushSearch.whereEndsWith
RushSearch.whereContains
RushSearch.whereLike

All added in v1.1.7

Thanks
