### ISSUE TITLE
Support for FOREING KEY

### ISSUE THREAD

**Issue by gcalaprice** [Stuart-campbell/RushOrm#50]
Hi Stuart, is there a way to implement the FOREIGN KEY support in the table creations? I want to reference the primary key of a table into another table as foreign key, but I cannot find a way to achieve this situation.

Thanks.

**Comment by Stuart-campbell** [comment]
Hi,

Saving children is supported through join tables not foreign keys this is so that lists can be supported.

I'm not too sure why you would want to manually force a foreign key?

Thanks

**Comment by gcalaprice** [comment]
Hi Stuart,
can you show me an usage example of join tables using RushORM?

Let's say I have a two tables with one to many relationship: User and Car.

User (userId, name, surname)
Car (carId, userId, carModel)

So, one user can have multiple cars.

Thanks a lot for the support.

**Comment by Stuart-campbell** [comment]
class Car extends RushObject {
          String colour;
    }

    class User extends RushObject {
        @RushList(className = Car.class)
        List<Car> cars;
    }

Save and load as with any other object and all the children will still be there.

Thanks

**Comment by gcalaprice** [comment]
Hi Stuart, thanks for the advice. I want now to perform a DELETE CASCADE of the children objects when I delete the parent object.
With the RushCore "deleteAll()" method we are deleting the parent and the join tables. After I perform another delete on the child table given the parent ID to clean the relationship.
Is there another way to do this?

Thanks in advance.

**Comment by Stuart-campbell** [comment]
Hi,

By default all the children are deleted when the parent is deleted. So it already does what you want by just calling delete() on the parent. The default is also batched for best performance.

If you don't want the children to be deleted when you call delete on the parent add

    @RushDisableAutodelete

to the child field.

Thanks

**Comment by gcalaprice** [comment]
Hi Stuart, thanks a lot for the suggestion. It works like a charm!
