### ISSUE TITLE
String columns are limited to length 255

### ISSUE THREAD

**Issue by brocktriplets** [Stuart-campbell/RushOrm#52]
The size of the String columns are limited to 255.  Within RushColumnString the sqlColumnType is 
 public String sqlColumnType() {
        return "varchar(255)";
    }

Why?

If using SQL Lite, the column type should be TEXT, IMO.  Any reason for limiting to 255 ?

**Comment by Stuart-campbell** [comment]
Hi,

Reason is so the base classes in RushCore work with MySql as well.

If you have a look here http://sqlite.org/datatype3.html at the Type Affinity any column with "char" in is stored as "TEXT", so the underling result is the same.

Thanks

**Comment by brocktriplets** [comment]
Yep, re-read the SQL Documents
https://www.sqlite.org/faq.html#q9

varchar is text.  Thanks for thumping me on the head....
