### ISSUE TITLE
Add WHERE IN to RushSearch

### ISSUE THREAD

**Issue by kanashin** [Stuart-campbell/RushOrm#53]
Hello!

I really like RushOrm but I can't achieve the "WHERE IN" query.

Example. I want to do something like:
WHERE `column` IN (1,6,21)

Any idea?

Thank you!

**Comment by Stuart-campbell** [comment]
Hi,

Currently RushSearch does not have it. I'll mark this as a feature and add it in the next release.

For now you could do.

    List<String> values = // your values
    RushSearch rushSeach = new RushSearch();
    for(int i = 0; i < values.size(); i ++) {
        String value = values.get(i);
        rushSeach.whereEqual(column, value);
        if(i < values.size() - 1){
            rushSearch.or();
        }
    }
    List<Rush> results = rushSearch.find(Rush.class);

No as clean as it could be but hopefully does the job for now.

Thanks

**Comment by kanashin** [comment]
Thank you for your fast reply!

I have also achived it doing 

    String inStatement = "(";
    for (long item: items) {
        inStatement += String.valueOf(item) + ",";
    }
    inStatement = inStatement.substring(0, inStatement.length() - 1) + ")";

    RushWhereStatement rushWhereStatement = new RushWhereStatement(" column ", " in ", inStatement);
    RushSearch rushSearchArticle = new RushSearch();
    rushSearchArticle.getWhereStatements().add(rushWhereStatement);
    final List<Article> articles = rushSearchArticle.find(Article.class);

Anyway, I love RushOrm even more because without this feature is flexible enough to do complicated query.

Maybe for the next release, as you comment, it could be something like whereIn(field, List<String>) but as you want.

Thank you!

**Comment by Stuart-campbell** [comment]
Added in v1.1.8

Thanks
