### ISSUE TITLE
Documentation: Add hint about built-in RushObjects to troubleshooting section

### ISSUE THREAD

**Issue by phihos** [Stuart-campbell/RushOrm#58]
Hi,

as described in the troubleshooting section, I encountered problems with the default class loader and added a list of entities myself. One of these entities depended on RushBitmapFile, which I forgot to add to this list. 
I know, that I could have thought of this earlier, but I spend a few hours on debugging, because of a NullPointerException during table creation.

To prevent others from making the same mistake, I suggest to add a hint to the troubleshooting section to include all used built-in entities as well.

Another solution might be to always load built-in entities, even if a list of entity classes is provided by the user.

**Comment by Stuart-campbell** [comment]
Hi,

Fallen victim to this myself a few times. My intention is to add a new exception at the first point where you could access a tables that has not be created and identify this as the likely cause. Should have this done in the next week or two.

Thanks

**Comment by Stuart-campbell** [comment]
Added v1.1.8 so now you should get a helpful exception if the class you are loading or saving can not be found.
