### ISSUE TITLE
Documentation: Add section about proguard

### ISSUE THREAD

**Issue by phihos** [Stuart-campbell/RushOrm#59]
Hi,

after minifying my app with proguard, the RushOrm library tells me, that it can not find certain tables ( something like table rush_a_a_b_b not found). After adding something like

```
-keep class com.example.models.** { *; }
```
to the proguard.-rules.pro file, my app worked. 

A section in the docs about how to properly use proguard with RushOrm would help the users to get it right on the first try.

**Comment by Stuart-campbell** [comment]
After a day of using proguard myself I couldn't agree more libraries that don't have a proguard docs are very annoying.

I have not tested this yet myself, but I am wondering if you still get that exception from a clean install with proguard, as the tables should be created using the proguard class names.

Although I wonder even if that worked would it really mess things up if you updated your app and the obfuscated names all changed.

I'll do a few tests to check that out then add a proguard section based on my results.

Thanks

**Comment by phihos** [comment]
I also thought, that it might come from switching between the minfied and unminified version of my app without a clean install in between. 
But I already double checked that. In my case it already crashes somewhere during the Rush initialization (probably during table creation I guess).

**Comment by Stuart-campbell** [comment]
Ah ok that saves me some time, I have always used with gson so exclude my modal be default which is why I have missed it.

Thanks for pointing that out.

**Comment by Stuart-campbell** [comment]
Did you also need to include

    -keepattributes *Annotation*

**Comment by Stuart-campbell** [comment]
Added http://www.rushorm.com/#Proguard

This line might be a little more robust than just excluding your model package

    -keep public class * implements co.uk.rushorm.core.Rush { *; }

Thanks

**Comment by phihos** [comment]
Ah, I did not know that way to do it. I have only very shallow knowledge about proguard. Thanks for your quick action :-)
