### ISSUE TITLE
Loading saved data fails with java.lang.NumberFormatException: Invalid long: "true"

### ISSUE THREAD

**Issue by mrsasha** [Stuart-campbell/RushOrm#6]
Hi, I implemented it on 4 objects, and the saving works fine, but then loading the saved data gives the following exception:

02-18 09:37:35.929: E/AndroidRuntime(18171): java.lang.NumberFormatException: Invalid long: "true"
02-18 09:37:35.929: E/AndroidRuntime(18171): 	at java.lang.Long.invalidLong(Long.java:124)
02-18 09:37:35.929: E/AndroidRuntime(18171): 	at java.lang.Long.parse(Long.java:361)
02-18 09:37:35.929: E/AndroidRuntime(18171): 	at java.lang.Long.parseLong(Long.java:352)
02-18 09:37:35.929: E/AndroidRuntime(18171): 	at java.lang.Long.parseLong(Long.java:318)
02-18 09:37:35.929: E/AndroidRuntime(18171): 	at co.uk.rushorm.core.implementation.RushColumnLong.deserialize(RushColumnLong.java:22)
02-18 09:37:35.929: E/AndroidRuntime(18171): 	at co.uk.rushorm.core.implementation.RushColumnLong.deserialize(RushColumnLong.java:9)
02-18 09:37:35.929: E/AndroidRuntime(18171): 	at co.uk.rushorm.core.implementation.RushColumnsImplementation.setField(RushColumnsImplementation.java:50)
02-18 09:37:35.929: E/AndroidRuntime(18171): 	at co.uk.rushorm.core.implementation.ReflectionClassLoader.loadClass(ReflectionClassLoader.java:108)
02-18 09:37:35.929: E/AndroidRuntime(18171): 	at co.uk.rushorm.core.implementation.ReflectionClassLoader.loadClasses(ReflectionClassLoader.java:59)
02-18 09:37:35.929: E/AndroidRuntime(18171): 	at co.uk.rushorm.core.implementation.ReflectionClassLoader$1.doAction(ReflectionClassLoader.java:176)
02-18 09:37:35.929: E/AndroidRuntime(18171): 	at co.uk.rushorm.core.implementation.ReflectionClassLoader.doLoop(ReflectionClassLoader.java:242)
02-18 09:37:35.929: E/AndroidRuntime(18171): 	at co.uk.rushorm.core.implementation.ReflectionClassLoader.addChildrenToList(ReflectionClassLoader.java:152)
02-18 09:37:35.929: E/AndroidRuntime(18171): 	at co.uk.rushorm.core.implementation.ReflectionClassLoader.loadClasses(ReflectionClassLoader.java:68)
02-18 09:37:35.929: E/AndroidRuntime(18171): 	at co.uk.rushorm.core.implementation.ReflectionClassLoader.loadClasses(ReflectionClassLoader.java:47)
02-18 09:37:35.929: E/AndroidRuntime(18171): 	at co.uk.rushorm.core.RushCore.load(RushCore.java:274)
02-18 09:37:35.929: E/AndroidRuntime(18171): 	at co.uk.rushorm.core.RushCore.access$100(RushCore.java:28)
02-18 09:37:35.929: E/AndroidRuntime(18171): 	at co.uk.rushorm.core.RushCore$2.callback(RushCore.java:123)
02-18 09:37:35.929: E/AndroidRuntime(18171): 	at co.uk.rushorm.android.AndroidRushQueProvider$1.run(AndroidRushQueProvider.java:41)
02-18 09:37:35.929: E/AndroidRuntime(18171): 	at java.lang.Thread.run(Thread.java:811)

**Comment by Stuart-campbell** [comment]
Did you at some point change a boolean field to a long? Reinstalling the app would fix it if that is the problem.

**Comment by mrsasha** [comment]
No, it was just a test of saving and loading, performed in onPause and onResume, so it saved and then failed to load 0.5s later.

**Comment by Stuart-campbell** [comment]
Could you share the class that fails to load?

**Comment by mrsasha** [comment]
It seems to fail on this one (I removed the serialized names, but left @Getter @Setter used by lombok): 

public class User extends RushObject implements BasicUserDataInterface, Serializable {

    @Getter
    @Setter
    private long mUserId;

    @Getter
    private long mActualId;

    @Getter
    @Setter
    private String mDistance;

    @Getter
    @Setter
    private Date mBirthday;

    @Getter
    @Setter
    private String mGender;

    @Getter
    @Setter
    private Date mCreatedAt;

    @Getter
    private String mStatusMessage;

    private boolean mIsHereNow;

    
    @Getter
    private Float mRank;

    
	}

**Comment by Stuart-campbell** [comment]
So you found quite a weird bug here. Turns out I forgot to add a float column serializer. Which I shall add to the top of the todo list.

What is strange is changing 'Float' to 'float' stopped it crashing. Anyway if you replace the float with a double it will work for now.

Thanks for reporting this, I shall close it off once fixed.

Thanks

**Comment by mrsasha** [comment]
A small update - I tried replacing all floats with doubles, but it still crashes:

02-18 15:27:23.676: E/AndroidRuntime(27539): FATAL EXCEPTION: Thread-19933
02-18 15:27:23.676: E/AndroidRuntime(27539): Process: com.mbrace.android.alpha, PID: 27539
02-18 15:27:23.676: E/AndroidRuntime(27539): java.lang.NumberFormatException: Invalid long: "1.42408e+09"
02-18 15:27:23.676: E/AndroidRuntime(27539): 	at java.lang.Long.invalidLong(Long.java:124)
02-18 15:27:23.676: E/AndroidRuntime(27539): 	at java.lang.Long.parse(Long.java:361)
02-18 15:27:23.676: E/AndroidRuntime(27539): 	at java.lang.Long.parseLong(Long.java:352)
02-18 15:27:23.676: E/AndroidRuntime(27539): 	at java.lang.Long.parseLong(Long.java:318)
02-18 15:27:23.676: E/AndroidRuntime(27539): 	at co.uk.rushorm.core.implementation.RushColumnLong.deserialize(RushColumnLong.java:22)
02-18 15:27:23.676: E/AndroidRuntime(27539): 	at co.uk.rushorm.core.implementation.RushColumnLong.deserialize(RushColumnLong.java:9)
02-18 15:27:23.676: E/AndroidRuntime(27539): 	at co.uk.rushorm.core.implementation.RushColumnsImplementation.setField(RushColumnsImplementation.java:50)
02-18 15:27:23.676: E/AndroidRuntime(27539): 	at co.uk.rushorm.core.implementation.ReflectionClassLoader.loadClass(ReflectionClassLoader.java:108)
02-18 15:27:23.676: E/AndroidRuntime(27539): 	at co.uk.rushorm.core.implementation.ReflectionClassLoader.loadClasses(ReflectionClassLoader.java:59)
02-18 15:27:23.676: E/AndroidRuntime(27539): 	at co.uk.rushorm.core.implementation.ReflectionClassLoader$1.doAction(ReflectionClassLoader.java:176)
02-18 15:27:23.676: E/AndroidRuntime(27539): 	at co.uk.rushorm.core.implementation.ReflectionClassLoader.doLoop(ReflectionClassLoader.java:242)
02-18 15:27:23.676: E/AndroidRuntime(27539): 	at co.uk.rushorm.core.implementation.ReflectionClassLoader.addChildrenToList(ReflectionClassLoader.java:152)
02-18 15:27:23.676: E/AndroidRuntime(27539): 	at co.uk.rushorm.core.implementation.ReflectionClassLoader.loadClasses(ReflectionClassLoader.java:68)
02-18 15:27:23.676: E/AndroidRuntime(27539): 	at co.uk.rushorm.core.implementation.ReflectionClassLoader.loadClasses(ReflectionClassLoader.java:47)
02-18 15:27:23.676: E/AndroidRuntime(27539): 	at co.uk.rushorm.core.RushCore.load(RushCore.java:274)
02-18 15:27:23.676: E/AndroidRuntime(27539): 	at co.uk.rushorm.core.RushCore.access$100(RushCore.java:28)
02-18 15:27:23.676: E/AndroidRuntime(27539): 	at co.uk.rushorm.core.RushCore$2.callback(RushCore.java:123)
02-18 15:27:23.676: E/AndroidRuntime(27539): 	at co.uk.rushorm.android.AndroidRushQueProvider$1.run(AndroidRushQueProvider.java:41)
02-18 15:27:23.676: E/AndroidRuntime(27539): 	at java.lang.Thread.run(Thread.java:811)

**Comment by mrsasha** [comment]
it seems it's not recognizing classes for serialization/deserialization correctly.

**Comment by Stuart-campbell** [comment]
Are you able to test off the current main? I have not been able to build a new jar yet. I thinking a counter++ had got itself in the wrong loop, which was meaning the wrong deserialization was being used.

**Comment by Stuart-campbell** [comment]
I have post an updated jar which should resolve this bug.

**Comment by Stuart-campbell** [comment]
Has this been resolved? Just looking to close this issue off.

Thanks

**Comment by mrsasha** [comment]
Hi, sorry I was a bit late. It looks like it doesn't happen anymore.
