### ISSUE TITLE
How to return unique/distinct rows from a table - DISTINCT

### ISSUE THREAD

**Issue by ggunders** [Stuart-campbell/RushOrm#60]
I would like to be able to return unique rows from a RushSearch(). 

    select distinct a, * from table_name;

where a is the field name(column name).

**Comment by Stuart-campbell** [comment]
Good idea. Should be able to add this for the next release in a week or so.

Thanks

**Comment by Stuart-campbell** [comment]
Hi,

On reviewing this, not too sure how it would be achieved without returning the raw cursor.

But I think what will get you the result your after is "group by" as this will give you a object in return and no duplicates of the field you group by.

    rushSearch.groupBy(field).find(class);

Thanks
