### ISSUE TITLE
Crashes because of RushCoreNotInitializedException

### ISSUE THREAD

**Issue by fabsimilian** [Stuart-campbell/RushOrm#62]
We're getting a lot of crashes because of the RushCoreNotInitializedException. 
Is there a way that RushOrm itself checks if it is initialized? I think this error happens, when an app comes from the background and android was killing some resources... 
Is there any proper way to handle this exception or should we check ourself? :)
We're using rushorm 1.1.5 - can we update to 1.1.7 without any problems or data loss?

**Comment by Stuart-campbell** [comment]
Hi,

Where about do you call initialize?

Thanks

**Comment by fabsimilian** [comment]
Hi, thanks for the quick reply! 
We've an own SplashScreen for that and we're initializing rushorm in an AsyncTask:

    private class RushTask extends AsyncTask<Void, Void, Void> {
        @Override
        protected Void doInBackground(Void... params) {
            RushAndroid.initialize(getApplicationContext());
            mRushInitialized = true;
            goToMainActivity(); //starts main activity 
            return null;
        }
    }

the splashscreen is only called if the app is restarted but not when openend from background.

**Comment by Stuart-campbell** [comment]
Yes thats not going to be the post robust place to do it.

Here is an example of how I would suggest doing it.

First you need a singleton to access from anywhere.

    class MySingleton {
        static MySingleton singleton = new MySingleton();
        public static MySingleton getInstance() {
            return singleton;
        }

        boolean loaded = false;
        LoadedListener loadedListener;
        public interface LoadedListener {
            void loaded();
        }

        public void setLoadedListener(LoadedListener loadedListener) {
            this.loadedListener = loadedListener;
        }

        public void setLoaded(boolean loaded) {
            loaded = true;
            if(loadedListener != null) {
                loadedListener.loaded();
            }
        }

        public boolean getLoaded(){
            return loaded;
        }
    }

Then you want to call initialize in the application class (need to set it in the manifest) Tell the singleton when its loaded

    class MyApplication extends Application {
      @Override
      public void onCreate() {
        super.onCreate();
        AndroidInitializeConfig androidInitializeConfig = new AndroidInitializeConfig(getApplicationContext());
        androidInitializeConfig.setInitializeListener(new InitializeListener() {
            @Override
            public void initialized(boolean b) {
                // Not called back on main thread
                Handler mainHandler = new Handler(getApplicationContext().getMainLooper());
                mainHandler.post(new Runnable() {
                    @Override
                    public void run() {
                        MySingleton.getInstance().setLoaded(true);
                    }
                });
            }
        });
        RushAndroid.initialize(androidInitializeConfig);
      }
    }

In your splash activity's onCreate

     @Override
    protected void onCreate(Bundle savedInstanceState) {
         super.onCreate(savedInstanceState);
        setContentView(R.layout.layout);
        if (MySingleton.getInstance().isLoaded()) {
            showMainActivity();
        } else {
           MySingleton.getInstance().setLoadedListener(new MySingleton.LoadedListener() {
                @Override
                public void loaded() {
                    showMainActivity();
                }
            });
        }
    }


As a side note id have a read of this https://plus.google.com/+AndroidDevelopers/posts/Z1Wwainpjhd its the new splash screen google is selling.

Thanks

**Comment by fabsimilian** [comment]
Thank you! I will try this. 
And do you know if there are any issues updating from 1.1.5 to 1.1.7?

**Comment by Stuart-campbell** [comment]
No actually quite an important fix for the auto migration, added LIKE and moved to use the config object above. Nothing that should cause issue.

**Comment by fabsimilian** [comment]
Perfect! So a big thanks for your quick replies. I'll try your suggestions.

**Comment by fabsimilian** [comment]
Hm the AndroidRushConfig does not contain a setInitializeListener() method..
