### ISSUE TITLE
Custom primary key

### ISSUE THREAD

**Issue by LimitTech** [Stuart-campbell/RushOrm#63]
Hello!

I was thinking about using a custom primary key (i.e. a combination of two fields).
Is that possible?

Thank you.

**Comment by Stuart-campbell** [comment]
Hi,

I think what you are looking for is

    RushObject object = new RushObject();
    RushCore.getInstance().registerObjectWithId(object, customId);
    object.save();

Important thing here is to register it before saving then it will use that id in the database.

If this is not what you men't let me know and ill try and answer.

Thanks

**Comment by JoniDS** [comment]
"RushCore.getInstance().registerObjectWithId(object, customId);"
Will only have a 1 field primary key.
I believe the request is to have a composite primary key (i.e. 2 or more fields).

**Comment by Stuart-campbell** [comment]
Ah,

Rush does not support Composite Primary Keys.

As Rush class (tables) are defined via an interface not too sure of a good approach to add the feature.

A possible way to approach this is the future would be to give more control over the table generation though annotates.
