### ISSUE TITLE
Performance on startup

### ISSUE THREAD

**Issue by fabsimilian** [Stuart-campbell/RushOrm#64]
Hi Stuart, 

I've one more question. Starting my application takes very long. The bottleneck is the Rush initialize. It takes around 4 seconds

        <meta-data
            android:name="Rush_db_version"
            android:value="3" />
        <meta-data
            android:name="Rush_db_name"
            android:value="appdatabase.db" />
        <meta-data
            android:name="Rush_debug"
            android:value="false" />
        <meta-data
            android:name="Rush_requires_table_annotation"
            android:value="false" />

I've already deactivated the debug option - but still it takes around 3 to 4 seconds. 
Is there anything I can speed up when initializing?

**Comment by Stuart-campbell** [comment]
Hi,

This is pretty odd. It should be instant after the db is created. Are you doing any updates to RushObjects when you start it?

Thanks

**Comment by fabsimilian** [comment]
Hi, 
nope, I just call Rush init, nothing else, and this takes around 3-4 seconds. And I can't do any RushObject updates before the init is done. (RushNotInitException) 
Event if i just restart the app it takes a few seconds..

**Comment by Stuart-campbell** [comment]
Can you add 

    <meta-data android:name="Rush_log" android:value="true" />

to your manifest file and check if any sql is being run.

Thanks

**Comment by fabsimilian** [comment]
Hi I just checked the logs - no sql is running on startup. 
This code is in my onCreate of the ApplicationClass

        /* BEGIN RUSH */
        final AndroidInitializeConfig config = new AndroidInitializeConfig(getApplicationContext());
        config.setInitializeListener(new InitializeListener() {
            @Override
            public void initialized(boolean b) {
                // Not called back on main thread
                Handler mainHandler = new Handler(getApplicationContext().getMainLooper());
                mainHandler.post(new Runnable() {
                    @Override
                    public void run() {
                        Toast.makeText(getApplicationContext(), "RushStartTimeTime " + (System.currentTimeMillis() - startTime), Toast.LENGTH_SHORT).show();
                        RushInitSingleton.getInstance().setLoaded(true);
                    }
                });
            }
        });

        new AsyncTask<Void, Void, Void>(){

            @Override
            protected Void doInBackground(Void... params) {
                startTime = System.currentTimeMillis();
                RushAndroid.initialize(config);
                return null;
            }
        }.execute();

         /* END RUSH */

And it takes around 5-6 seconds - every time

**Comment by Stuart-campbell** [comment]
Eeek AsyncTasks.

Taking it out the async task should fix it. It is already async. I always get the fear from AsyncTask due to how the share threads and the magic they get up to.

Let me know whats happens when initialize is just called in onCreate.

Thanks

**Comment by fabsimilian** [comment]
If I take RushAndroid.initialize out of Asynctask then the UI is freezing until it's done. And still takes around 5-6 seconds

**Comment by Stuart-campbell** [comment]
Is any SQL being logged during start up?

**Comment by fabsimilian** [comment]
nope no sql logged during startup

**Comment by Stuart-campbell** [comment]
Clutching a strews a little bit but do you have quite a lot of libraries in your project?

If so it might be the class finding is really slow.
Which would be fixed by settings your RushClasses rather than letting the library find them.

    List<Class<? extends Rush>> classes = new ArrayList<>();
    classes.add(MyClassA.class);
    classes.add(MyClassB.class);
    androidInitializeConfig.setClasses(classes);

If you use any of the RushFile classes you need to add them as well.

**Comment by fabsimilian** [comment]
Hm good hint - I'll try this. 
Do I have to add only the model classes or also the RushCore / RushSearch classes and so on?

**Comment by Stuart-campbell** [comment]
Just your model classes. Anything that extends RushObject. You will only have to add RushTextFile if you use it and RushBitmapFile.

Feature coming soon is defining your model package which should remove this issue as the number of search class to search will be tiny.

**Comment by fabsimilian** [comment]
That was the bottleneck! Now RushInit takes around 600ms! 
Thank you very much!!!

**Comment by Stuart-campbell** [comment]
No problem. Thanks for reporting. I'll up the priority of defining your model location, seems like that will solve a number of issues.

Cheers
