### ISSUE TITLE
Enum support

### ISSUE THREAD

**Issue by jd-alexander** [Stuart-campbell/RushOrm#65]
Does this ORM have support for enums?

**Comment by Stuart-campbell** [comment]
I have not testing but my guess would be no.

But here is how you could implement your own column type to save your enum.

    static class EnumColumn implements RushColumn<MyEnum> {

        @Override
        public String sqlColumnType() {
            return "integer";
        }

        @Override
        public String serialize(MyEnum myEnum, RushStringSanitizer rushStringSanitizer) {
            return rushStringSanitizer.sanitize(Integer.toString(myEnum.ordinal()));
        }

        @Override
        public MyEnum deserialize(String s) {
            return MyEnum.values()[Integer.parseInt(s)];
        }

        @Override
        public Class[] classesColumnSupports() {
            return new Class[]{MyEnum.class};
        }
    }

Then start Rush like this

    AndroidInitializeConfig androidInitializeConfig = new AndroidInitializeConfig(context);
    androidInitializeConfig.addRushColumn(new EnumColumn());
    RushAndroid.initialize(androidInitializeConfig);

Thanks
