### ISSUE TITLE
char field

### ISSUE THREAD

**Issue by joancifo** [Stuart-campbell/RushOrm#67]
Hello again!

I saw that a char field isn't stored in the database, could it be?

It's true that I can use a String to wrap a char, but a char is smaller and cuter in some situations.
I know that in sqlite a char and a string are saved equally. I'm talking about the Android source.

Thank you!

**Comment by Stuart-campbell** [comment]
Yes there is no default Char column. Seems fair to add one so ill mark this as an enhancement.

For now you can just do it yourself and add a custom column.

    class RushColumnChar implements RushColumn<Character> {
        @Override
        public String sqlColumnType() {
            return "varchar(255)";
        }

        @Override
        public String serialize(Character object, RushStringSanitizer stringSanitizer) {
            return stringSanitizer.sanitize(object != null ? object.toString() : null);
        }

        @Override
        public Character deserialize(String value) {
            return value.length() > 0 ? value.charAt(0) : null;
        }

        @Override
        public Class[] classesColumnSupports() {
            return new Class[]{Character.class, char.class};
        }
    }

Then start rush like this

    AndroidInitializeConfig androidInitializeConfig = new AndroidInitializeConfig(context);
    androidInitializeConfig.addRushColumn(new EnumColumn());
    RushAndroid.initialize(androidInitializeConfig);

Untested answer but should do the job.

Thanks

**Comment by kanashin** [comment]
Thanks!
