### ISSUE TITLE
Issues with booleans

### ISSUE THREAD

**Issue by joancifo** [Stuart-campbell/RushOrm#69]
Hello again!

I'm having issues with boolean fields.

I have the model with next fields:

```
public int codi;
public boolean actiu;
```

Next search return null:

```
new RushSearch().where('actiu', false).find(MyModel.class)
// Although I saw in code you do Boolean.toString(value), I have also tried 
new RushSearch().where('actiu', 'false').find(MyModel.class) // with the same result
```

But looking into sqlite file I see

```
5ff86f7b-7d9c-4242-9e71-5094b2c3d137|1438939245151|1438939245152|1|false
```

I'm storing models from React using

```
new RushCore().getInstance().save(list)
```

ATM I solved it using integer instead of boolean (I know that in sqlite the 'boolean' field is special and it should be saved as a 0/1 integer).

**Comment by kanashin** [comment]
Well, I have investigated more.

I see if I have a JSON with a field "1" (with slashes) is always saved as false (without slashes) if field is boolean. But if the field is integer it is saved as 1.
