### ISSUE TITLE
Finding objects where a field is null

### ISSUE THREAD

**Issue by DavidBennettUK** [Stuart-campbell/RushOrm#72]
Is there any support for querying for objects with a null field? Something like RushSearch.whereNull/whereNotNull would be great, unless I'm missing something. 

I have a model with a date field that can be null, and would like to find all of these instances, but I can't find any methods in RushSearch that will help me do so.

**Comment by DavidBennettUK** [comment]
Created a pull request to add this functionality. See https://github.com/Stuart-campbell/RushCore/pull/2

**Comment by Stuart-campbell** [comment]
Hi,

Good suggestion I have merged your changes into RushCore. I will do an updated release shortly.

Thanks

**Comment by Stuart-campbell** [comment]
Added in v1.1.10 sorry for the delay.
