### ISSUE TITLE
Incorrect logic with ReflectionUtils.getAllFields() method - wrong order of fields

### ISSUE THREAD

**Issue by HitOdessit** [Stuart-campbell/RushOrm#73]
Hi Stuart,

Recently I've stumbled an interesting issue - if you save some data into database file and load it later on the same Android OS version (read same JVM) everything works as expected. But if you load that .db file on another Android OS version, data can't be loaded, lots of crashes.

I've made some research on this issue and found root cause - your logic in `ReflectionClassLoader .loadClass(...):104` method assumes that utility method `ReflectionUtils.getAllFields()` returns list of class fields always in the same order. But this is not the case. Quote from Java API:
http://docs.oracle.com/javase/7/docs/api/java/lang/Class.html#getFields()

    Returns an array containing Field objects reflecting all the accessible public fields of the class or interface represented by this Class object. 
    The elements in the array returned are not sorted and are not in any particular order. 
    This method returns an array of length 0 if the class or interface has no accessible public fields, or if it represents an array class, a primitive type, or void.

So, I think logic of using `ReflectionUtils.getAllFields()` method should be changed.

**Comment by Stuart-campbell** [comment]
Good point, had not thought about database cross device compatibility.

Not a problem to sort fields alphabetically, only problem it is would break it for everyone else.

Maybe have an option to do so in the config with the default not.

Thanks

**Comment by HitOdessit** [comment]
Hi Stuart, any updates on this issue?
For me, it looks like a major issue, 'cos user simply need to update OS version on his device and any app based on RushORM simply will break. Pretty critical, as for me.

**Comment by Stuart-campbell** [comment]
Hi,

Sorry been meaning to get round to it.
I will get it fixed this weekend.

Thanks

**Comment by Stuart-campbell** [comment]
Just updated to v1.1.10 where you can add the following meta-data to the manifest

    <meta-data android:name="Rush_order_alphabetically" android:value="true" />

This should order all the fields so will be cross device compatible.

Thanks

**Comment by nmoskalenko** [comment]
@Stuart-campbell , as I understood form your commit https://github.com/Stuart-campbell/RushOrm/commit/6e4609a73960a42d08d17da0347d12cfbab3e4c8 you specified this behavior only for JSON serialization/deserialization purposes ? Or I misunderstood? 
This is not the case.
What we need is the availability to use some database on different devices natively.
For example generate database on emulator, copy to real device and use via RushORM without any additional manipulations.

**Comment by Stuart-campbell** [comment]
Hi,

The key to that commit is the change in Subproject commit number.

All fields can now be order alphabetically into the database not just json. I only added it to the json for consistency, I understand an ordered json is pretty useless.

Here is a link to the changes that should fix your issue be making the order of getAllFields the same regardless of device https://github.com/Stuart-campbell/RushCore/commit/70dbe6ee4f3c9b70c12400aa68694e719d70b0ac

Thanks
