### ISSUE TITLE
Upon using RushSearch, a NullPointerException is thrown

### ISSUE THREAD

**Issue by yesitspeter** [Stuart-campbell/RushOrm#74]
I'm getting the following:
I'm calling

    new RushSearch().find(ImageCorrections.class)

Then I get:

    java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.String co.uk.rushorm.core.AnnotationCache.getTableName()' on a null object reference
    at co.uk.rushorm.core.RushSearch.buildSql(RushSearch.java:90)
    at co.uk.rushorm.core.RushSearch.find(RushSearch.java:41)
 

Here is my Application onCreate:

       List<Class<? extends Rush>> classes = new ArrayList<>();
        classes.add(OptionSet.class);
        classes.add(OptionSetOption.class);
        classes.add(ListReference.class);
        classes.add(Option.class);
        classes.add(OptionValue.class);
        classes.add(PriceAdjuster.class);
        classes.add(Product.class);
        classes.add(ProductCategory.class);
        classes.add(ProductOption.class);
        classes.add(ProductRule.class);
        classes.add(Reference.class);
        classes.add(ImageCorrection.class);
        classes.add(ImageCorrections.class);
        classes.add(ImageRule.class);
        classes.add(ImageRules.class);
        classes.add(OffsetCorrection.class);
        classes.add(ScaleCorrection.class);

        AndroidInitializeConfig config = new AndroidInitializeConfig(getApplicationContext());
        config.setClasses(classes);
        RushCore.initialize(config);

**Comment by Stuart-campbell** [comment]
Hi,

Does ImageCorrections have any other RushObjects as children?
Are you trying to load synchronously after calling initialize?

Thanks

**Comment by Stuart-campbell** [comment]
Closing as no reply if still valid reopen.
