### ISSUE TITLE
Fatal Exception: RushSqlException

### ISSUE THREAD

**Issue by ociata** [Stuart-campbell/RushOrm#79]
Hey,

I'm using your project which is pretty good and solid. I have the following problem: I'm unable to flawlessly update my app database. I keep getting RushSqlException error until I delete the app from device and install it again. This is in my manifest:

    
    <meta-data android:name="Rush_db_version" android:value="3" />

    
    <meta-data android:name="Rush_db_name" android:value="iag.db" />

    
    <meta-data android:name="Rush_debug" android:value="false" />

    
    <meta-data android:name="Rush_requires_table_annotation" android:value="false" />

    
    <meta-data android:name="Rush_log" android:value="false" />

I'm using version 1.1.10. Could you please point me how to resolve this issue?

**Comment by stuart-apadmi** [comment]
Hi could you set Rush_log to true add see if any helpful info is logged out.

Thanks

**Comment by todorovhristo** [comment]
Hi and thank you for your quick reply. The problem appears to be that I was setting metadata on `Manifest`(main) level, instead of `Application`. After moving it on the correct place everything start working again. It was a noob error, I must admit it :)

**Comment by Stuart-campbell** [comment]
No worries also it seems I commented from multiple accounts as well..
