### ISSUE TITLE
Null pointer exception during instruction 'invoke-static {v4}

### ISSUE THREAD

**Issue by ggunders** [Stuart-campbell/RushOrm#80]
i get this null pointer exception occasionally. The only way to get rid of it is to delete the database.

    Null pointer exception during instruction 'invoke-static {v4}, co.uk.rushorm.core.Rush co.uk.rushorm.core.implementation.ReflectionClassLoader$Join.access$100(co.uk.rushorm.core.implementation.ReflectionClassLoader$Join) // method@16795

       Evidence evidence = new RushSearch().whereEqual("timestamp", saved.getTimestamp()).and().whereEqual("cached", true).findSingle(Evidence.class);
                evidence.delete();
                saved.save();

**Comment by ggunders** [comment]
ok i updated to 1.1.10 and erased local databse rush.db. still get same null pointer on the RushSearch line.

**Comment by ggunders** [comment]
i should mention this is in an intent service off main thread

    java.lang.NullPointerException: Null pointer exception during instruction 'invoke-static {v4},     co.uk.rushorm.core.Rush    co.uk.rushorm.core.implementation.ReflectionClassLoader$Join.access$100(co.uk.rushorm.core.impl    ementation.ReflectionClassLoader$Join) // method@16800'
10-14 11:48:15.851 26143-27080/? E/AndroidRuntime:     at co.uk.rushorm.core.implementation.ReflectionClassLoader$1$1.attach(ReflectionClassLoader.java:208)
10-14 11:48:15.851 26143-27080/? E/AndroidRuntime:     at co.uk.rushorm.core.implementation.ReflectionClassLoader.loadClasses(ReflectionClassLoader.java:67)
10-14 11:48:15.851 26143-27080/? E/AndroidRuntime:     at co.uk.rushorm.core.implementation.ReflectionClassLoader$1.doAction(ReflectionClassLoader.java:200)
10-14 11:48:15.851 26143-27080/? E/AndroidRuntime:     at co.uk.rushorm.core.implementation.ReflectionClassLoader.doLoop(ReflectionClassLoader.java:272)
10-14 11:48:15.851 26143-27080/? E/AndroidRuntime:     at co.uk.rushorm.core.implementation.ReflectionClassLoader.addChildrenToList(ReflectionClassLoader.java:175)
10-14 11:48:15.851 26143-27080/? E/AndroidRuntime:     at co.uk.rushorm.core.implementation.ReflectionClassLoader.loadClasses(ReflectionClassLoader.java:73)
10-14 11:48:15.851 26143-27080/? E/AndroidRuntime:     at co.uk.rushorm.core.implementation.ReflectionClassLoader.loadClasses(ReflectionClassLoader.java:52)
10-14 11:48:15.851 26143-27080/? E/AndroidRuntime:     at co.uk.rushorm.core.RushCore.load(RushCore.java:608)
10-14 11:48:15.851 26143-27080/? E/AndroidRuntime:     at co.uk.rushorm.core.RushCore.load(RushCore.java:257)
10-14 11:48:15.851 26143-27080/? E/AndroidRuntime:     at co.uk.rushorm.core.RushSearch.find(RushSearch.java:41)
10-14 11:48:15.851 26143-27080/? E/AndroidRuntime:     at co.uk.rushorm.core.RushSearch.findSingle(RushSearch.java:32)
10-14 11:48:15.851 26143-27080/? E/AndroidRuntime:     at com.threetwofour.scribe.Network.MyIntentService.handleActionEvidence(MyIntentService.java:179)
10-14 11:48:15.851 26143-27080/? E/AndroidRuntime:     at com.threetwofour.scribe.Network.MyIntentService.onHandleIntent(MyIntentService.java:126)
10-14 11:48:15.851 26143-27080/? E/AndroidRuntime:     at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
10-14 11:48:15.851 26143-27080/? E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:102)
10-14 11:48:15.851 26143-27080/? E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:135)
10-14 11:48:15.851 26143-27080/? E/AndroidRuntime:     at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by ggunders** [comment]
the RushSearch is what fails. here is the entry in the database that does in fact exist

30d0c2f6-e337-4e5e-8b84-87307f001802|1444850061248|1444850061248|1|true|sdf|||1|1444850059666|General|0
sqlite> .schema rush_com_threetwofour_scribe_Models_Evidence 
CREATE TABLE rush_com_threetwofour_scribe_Models_Evidence (
rush_id varchar(255) primary key,
rush_created long,
rush_updated long,
rush_version long,
cached boolean,
description varchar(255),
itemNumber long,
removed boolean,
searchId long,
timestamp long,
type varchar(255),
evidence_id long
);

**Comment by ggunders** [comment]
This is becoming very annoying. its very similar to another issue. This is very similar to Issue #61. I can reproduce this more frequently now. its an issue with a parent object having multiple children of the same type. I cant hand over the entire project but can provide more code examples if necessary. Can i get some pointers on how to debug this error. thanks

**Comment by Stuart-campbell** [comment]
Closing with the same resolution as #61
