### ISSUE TITLE
issue using gson

### ISSUE THREAD

**Issue by zean** [Stuart-campbell/RushOrm#82]
i have this classes 

public class Server_Roster extends RushObject {

    @RushList(classType = MyRosterEntry.class)
    private ArrayList<MyRosterEntry> users;

    public Server_Roster() {
        users = new ArrayList<>();
    }

    public Server_Roster(ArrayList<MyRosterEntry> contacts) {
        this.users = contacts;
    }

    public ArrayList<MyRosterEntry> getContacts() {
        return users;
    }

}

public class MyRosterEntry extends RushObject {
    private final static String TAG = "MyRosterEntry";

    private String id;
    private String username;
    private String profile_image;
    private String type;
    private String created_at;
    private String updated_at;
    private String mobile_hash;
    private String friend_status;
    private String jid;
    private String display_name;
    private boolean is_blocked;
    private boolean blocked_by;
    private boolean to_delete;

    @RushIgnore
    private Activity activity;
    @RushIgnore
    private Chat_User chat_user;

    public MyRosterEntry() {
    }

    public MyRosterEntry(String id, String username, String profile_image, String type,
                         String created_at, String updated_at, String mobile_hash,
                         String friend_status, String jid, String display_name,
                         boolean is_blocked, boolean blocked_by, boolean delete) {
        this.id = id;
        this.username = username;
        this.profile_image = profile_image;
        this.type = type;
        this.created_at = created_at;
        this.updated_at = updated_at;
        this.mobile_hash = mobile_hash;
        this.friend_status = friend_status;
        this.jid = AuxiliarClass.getJid(jid);
        this.display_name = display_name;
        this.is_blocked = is_blocked;
        this.blocked_by = blocked_by;
        this.to_delete = delete;
    }

}

and this works fine if i use the constructors,
but when i use 
try {
            Gson gson = new Gson();
            JSONObject obj = new JSONObject(result);
            Server_Roster json = gson.fromJson(obj.toString(), Server_Roster.class);
            server_roster = new Server_Roster(json.getContacts());
        } catch (JSONException e) {
            Log.e(TAG, "JSONException", e);
            updateFinished("0");
        }

the app blocks in 
Server_Roster json = gson.fromJson(obj.toString(), Server_Roster.class);

you have any idea why?

this stopped working after i added the rushignore variables

Cheers mate

**Comment by Stuart-campbell** [comment]
Hi,

Not sure why this is happening could you share the json and ill try debugging it.

Cheers

**Comment by fabsimilian** [comment]
Just because I read the issue. Maybe gson cannot read the activity class? What about trying to annotate it with @Expose?

**Comment by zean** [comment]
i managed to fix this removing the activity from the class, must be that

**Comment by Stuart-campbell** [comment]
Closing but replaced with https://github.com/Stuart-campbell/RushOrm/issues/91
