### ISSUE TITLE
http://maven.rushorm.com and http://www.rushorm.com/ are down

### ISSUE THREAD

**Issue by dionisi** [Stuart-campbell/RushOrm#86]
The RushOrm website and the maven repo (http://maven.rushorm.com) which hosts the library are not accessible.

Unfortunately every project that has dependency to RushOrm can not be rebuild

**Comment by Stuart-campbell** [comment]
Hi,

Server needed restarted, sorry about that, keep meaning to get it on maven cental.

Cheers

**Comment by dionisi** [comment]
Thanks for the quick reactions. It works now.

Cheers!
