### ISSUE TITLE
there is already another table or index with this name: rush_co_uk_rushorm_android_RushJSONFile_temp

### ISSUE THREAD

**Issue by dco5** [Stuart-campbell/RushOrm#9]
Im getting:
there is already another table or index with this name: rush_co_uk_rushorm_android_RushJSONFile_temp
 java.lang.RuntimeException: Unable to create application org.hapl.haplapp.HAPL: android.database.sqlite.SQLiteException: there is already another table or index with this name: rush_co_uk_rushorm_android_RushJSONFile_temp (code 1): , while compiling: ALTER TABLE rush_co_uk_rushorm_android_RushJSONFile RENAME TO rush_co_uk_rushorm_android_RushJSONFile_temp

**Comment by Stuart-campbell** [comment]
Hi,

Sounds like during a previous upgrade it failed to clean up the temp tables created in the migration. Reinstalling will fix it for now, but looks like ill need to put a check in place.

Thanks

**Comment by dco5** [comment]
How can I re install it? Sorry I am really new to this...

**Comment by Stuart-campbell** [comment]
Fully uninstall you app and reinstall it. So that the old db is removed.

**Comment by dco5** [comment]
Oh ok... That would not be a good solution if it goes to production. I will wait for your fix. Thank you!

**Comment by Stuart-campbell** [comment]
Was unable to reproduce the bug, so couldn't test that it's fixed. Let me know if 1.0.3 does not do the job.

Thanks
