### ISSUE TITLE
Problem when saving many records using RushCore.getInstance().save(List<? extends Rush> objects). Not everything is persisted.

### ISSUE THREAD

**Issue by rhyek** [Stuart-campbell/RushOrm#96]
I'm deserializing around 5,000 objects from a JSON API and aggregating each to a list which I then try to save all at once. These objects are of different classes and there are several to-many and to-one relationships among them. The list contains every object that should exist in the database. Nested relationships are essentially flattened just for saving. Once the save finishes I'm noticing not everything is being persisted to the database. By this I don't mean relationships exactly. Actual records aren't being saved.

If I save each object one by one they are all saved normally, but this takes an extraordinary amount of time. Hours. When I save them all at the same time it takes around 30min which is also pretty bad, but the idea is this should only happen once ever so it's manageable. Sadly I'm guessing it takes less time since it's not actually saving everything.

Is there anything special one should know about using `RushCore.getInstance().save(List<? extends Rush> objects)`?

**Comment by Stuart-campbell** [comment]
That is pretty bad should really only take 60 seconds max for 5000 rows. I guessing you data structure is quite complicated so could be more like 50,000 rows. Could you upload your model and I can try to debug the problem.

The most obvious thing I can think of to speed it up is to implement custom columns for any objects that you don't need to search by rather than have them extend RushObject. You could also rap your lists in a class so you can do that for them as well. Details of implementing your own columns types at the link.

http://www.rushorm.com/advanced.html#Customise

Of course this stops RushSearch working on these classes so might not be helpful.

In terms of some data not being saved, I have a test checking 1000 rows looks like it need to check more...

Cheers

**Comment by rhyek** [comment]
I really need to be able to query all classes. I'll put together a small project for you to mess around with and let you know. It will include a real JSON payload, all models, and deserialization. But in general, even after deserializing, whenever I try to save a single complex record it can take around 3-4 seconds. I'll also try and demonstrate that.

If I understand it, when I have a record with nested relationships two or more levels deep, every record and relationship is saved recursively, correct? I suspect if there was a way to opt out of this behavior for those special cases it would speed things up a great deal.

Clear something up for me, if you could. Say I have this code:

````
class Parent extends RushObject {
    Child child;
}

class Child extends RushObject {
    Parent parent;
}

Parent parent1 = new Parent();
Child child1 = new Child();
parent1.child = child1;
child1.parent = parent1;

parent1.save();
child1.save();
```

Now, I understand in that specific case, saving child1 is redundant since `parent1.save()` persists it, yes? In my case, in the JSON payload I'm receiving I might get parents with no children or children with no parents, so to keep it simple I just save everything. But doing it that way saves both parent1, child1, and their relationships twice. Correct?

Thanks!

**Comment by Stuart-campbell** [comment]
Circular has been a bit of a headache... but should work.

Yes that will save everything twice.

It should not be that slow so I will have a look at it.

If it is a one off it might be worth having a read of this article, not really an option if per use data but might work for you. Could be adapted to download the actual DB file from the server so you don't have to shit the data with the app.

http://android-dev.mobi/blog/2015/05/17/rushorm-using-predefined-database-on-both-mobile-and-wear-apps/

**Comment by rhyek** [comment]
Stuart, I'm assuming it would be best to just avoid circular relationships to improve performance?

Say I have class A that has a list of records of class B, which themselves have a list of records of class C (A -> B -> C). Currently I also have upstream relationships such that I can navigate C -> B -> A. If I save a record of type C, that would mean I'm saving record type B, record type A, and all type B children of A, and finally all type C children of all those B records.

I could avoid all of this if I eliminated my upstream relationships and I imagine my performance would greatly improve. Do I have the right idea?

**Comment by Stuart-campbell** [comment]
Yeah that will be the problem.

There is a load of logic to stop each row being saved more than once, but it's batched into 1000 max root objects to keep memory under control. So if they are all referencing each other every row could be being saved a number of times which would explain why its so slow.

If you can get rid of the upstream relationships that should solve it.

Getting B in your example is easier than that as you don't need to add the parent id you can query the parent based on it's children.

    class B extends RushObject {
        private C c;

        @RushList(class = C.class)
        private List<C> cList;
    }

    class C extends RushObject {
        public B getB() {
            return new RushSeach()
                .whereEqual("c", this)
                .findSingle(B.class);
        }

        public B getBList() {
            return new RushSeach()
                .whereEqual("cList", this)
                .findSingle(B.class);
        }
    }

Thanks

**Comment by rhyek** [comment]
That's pretty convenient. I'll work on these changes and let you know how it goes. Mind if I run some tests after with the original problem of `RushCore.getInstance().save(List<? extends Rush> objects)` not saving all the records before closing the ticket?

**Comment by Stuart-campbell** [comment]
Yeah no problem if you can get a test proving it I can hopefully fix it. I have a feeling the issue will be when you start saving 1001+ objects.

**Comment by rhyek** [comment]
Lots of work atm. Haven't had time to really check this. Sorry. After the optimizations discussed here I don't have anymore issues.
